[ Docs ] Lint, Build, Assign Reviewer Workflow 생성
GAMZA-BAT/algohub-client pull request #13
Opened 2024-09-09 12:44 UTC by wuzoo

## #️⃣ Related Issue
Closes #7 

## ✅ Done Task
  - [ ] Lint
  - [ ] Build
  - [ ] Assign Reviewer

## ☀️ New-insight

1. 자동으로 리뷰어를 할당해주는 `action`은 `kentaro-m/auto-assign-action`를 통해 실행시킬 수 있다는 것을 알게되었습니다.
2. `NextJS`는 빌드 속도를 향상시키기 위해 빌드 간에 공유되는 것들을 `.next/cache`에 캐시로 저장하고 있습니다. 따라서 이에 대한 이점을 챙기기 위해서는 `CI Workflow`에 이에 대해서 작성해주는 것을 권장한다고 하네요 ! 이와 관련된 코드 또한 추가해두었습니다.
3. Lint 같은 경우에는 `biome` include 속성 수정한거 반영해서 workflow 내에서 `pnpm biome lint` 코드를 돌리도록 해두었습니다.

2024-09-09 13:47 UTC, ptyoiy commented on .github/workflows/build.yml
> +          path: out
action이 실패했길래 확인해보니 이 부분에서 에러가 나고 있어서 좀 찾아봤습니다.
[공식 문서](https://github.com/actions/upload-pages-artifact/blob/main/action.yml)에서 보니 정적 파일이 들어있는 경로를 입력하라고 나와있던데, actions/upload-pages-artifact를 사용하는 [다른 예시](https://vitepress.dev/ko/guide/deploy)를 찾아서 뭔 말인지 추론해보니 build 결과물인 dist폴더의 경로를 지정하라는 것 같아요!

2024-09-09 14:34 UTC, wuzoo commented on .github/workflows/build.yml
> +          path: out
그렇네요 ! 저도 다른 workflow 실패 뜨는 것좀 해결하고, 방금 `artifact`에 대해서 찾아보았는데, `path` 경로에 있는 작업물을 다운로드 가능한 하나의 파일을 만드는 과정이라고 하네요 !

도움 주셔서 감사합니다링 ~

2024-09-09 16:01 UTC, j-nary requested changes
LGTM! 코리 반영 부탁드림둥

2024-09-09 16:01 UTC, j-nary commented on biome.json
p3) 변경사항 지워주세용 !! 이미 머지 되어있숨다 그리구 console은 warn으로 유지시키는게 어떨까요?
꼭 필요한 콘솔도 있을 수 있으니까용

2024-09-09 16:01 UTC, j-nary commented on src/app/page.tsx
> +  console.log("biome ci test");
p1) 콘솔 지워주세용

2024-09-09 16:09 UTC, wuzoo commented on src/app/page.tsx
> +  console.log("biome ci test");
lint 테스트 하느라 잠시 커밋해놓은거라, 방금 다시 원상복구 해놨습니다 !

2024-09-09 16:09 UTC, wuzoo commented on biome.json
이것두용 !

2024-09-09 16:13 UTC, j-nary approved these changes

2024-09-09 17:35 UTC, hwangjokim reviewed
수고하셨습니다 :)

2024-09-09 17:35 UTC, hwangjokim commented on .github/workflows/build.yml
> +          path: .next
[P4]
저는 CI에서 실제 Production 빌드 및 아티팩트 업로드까지 이루어지면 안된다고 생각합니다.
책임의 분리 관점인데요, CI 레벨에서 정말 필요한 체크는 네 가지라고 생각합니다.

- tsc를 통한 타입스크립트 컴파일 (==컴파일타임 에러 검사)
- lint 검사
- 코드 포매팅 검사
- 테스트코드 존재시 테스트 코드 Run

위 네가지는 Production 빌드를 하지 않아도 검사가 가능한 부분이고, 통합테스트가 필요한 부분이 아닙니다.

또한 CI 파이프라인의 메인 사용처는 이런 PR입니다. 아티팩트는 업로드하면 버저닝으로 기록이 계속해서 남습니다. 업로드된 아티팩트를 시간순으로 볼 수 있고, 별도로 다운로드도 가능한데요, 이렇게 PR마다 모두 빌드 및 아티팩트 업로드를 반복하면 배포 단위, feature단위로 빌드가 나오지 않고 각종 PR의 trivial한 커밋에 대해서도 모두 히스토리가 생겨버려 아티팩트 관리가 어려워집니다.

결론은 컴파일 검사는 tsc로 하고, restore 캐시와 빌드, 업로드는 CD 파이프라인의 책임이 맞다고 생각합니다.

2024-09-10 04:38 UTC, wuzoo commented on .github/workflows/build.yml
> +          path: .next
상세한 피드백 감사드립니다 황조님 !

말씀 정말 이해완료했습니다. CI CD 파이프라인을 구축하는데 있어서도 이런 사소한 부분들이 정말 중요하다는 걸 다시금 깨닫고 가네요 ! 지금까지 워크플로우를 작성할 때, 항상 ci cd를 같은 부분에서 작성하곤 했는데, 황조님이 말씀하신 것처럼 불필요한 pr에서까지 빌드가 되고 아티팩트가 생성된다는 점, 그리고 특정 파일이 해당 파일의 순수한 책임을 다하지 못한다는 점에서 리뷰해주신 점이 와닿은 것 같습니다.

수정해서 반영하도록 하겠습니다 ~

2024-09-10 04:42 UTC, wuzoo commented on .github/workflows/build.yml
> +          path: .next
추가적으로 그렇다면 cd 파이프라인에 해당하는 부분은 `deploy` 브랜치에 pr 이 트리거되었을 때로 yml 파일을 따로 작성해서 생성해두면 될까요 ??

2024-09-10 08:36 UTC, j-nary approved these changes

2024-09-10 09:22 UTC, hwangjokim commented on .github/workflows/build.yml
> +          path: .next
배포하려면 제가 갖고있는 AWS에 접근해야하고, secrets들도 설정해야 하는 부분이라 CD yml은 제가 작성하겠습니다 :D
캐시쪽부터 아티팩트까지 잘 작성해주셔서 그대로 가져다 써도 될 것 같아요

2024-09-10 09:30 UTC, hwangjokim approved these changes
수고하셨습니다

2024-09-10 09:30 UTC, hwangjokim commented on .github/workflows/deploy-dev.yml
> +          path: .next
이것 잘 작성해주셔서 머지 이후 실제 artifact 다운로드 && deploy하는 부분 yml은 제가 이어서 해보겠습니다!

2024-09-10 11:32 UTC, wuzoo commented on .github/workflows/deploy-dev.yml
> +          path: .next
넵 ! 알겠습니다 ~

2024-09-10 11:34 UTC, ptyoiy approved these changes
고생 많으셨습니다!

2024-09-10 11:47 UTC, merged