[ Feat ] lottie 세팅
GAMZA-BAT/algohub-client pull request #18
Opened 2024-09-10 16:19 UTC by ptyoiy

## #️⃣ Related Issue
Closes #15 

## ✅ Done Task
  - [ ] 필요한 정적 파일 추가 (img, gif, json)
  - [ ] lottie 설치
  - [ ] lottie 컴포넌트 캡슐화

## ☀️ New-insight

lottie 애니메이션을 재생하려면 `react-lottie`나 `lottie-react` 패키지를 사용하면 됩니다. `react-lottie` 는 개발 중단되었고, 지속적인 업데이트가 이뤄지고 있는 `lottie-react` 패키지를 사용하였습니다.

라이브러리 사용법이 굉장히 간단명료합니다. 
아래 트러블 슈팅에서 자세한 내용을 확인해 주세요.
```typescript
<Lottie
	autoplay
	loop={loop}
	style={{ width: size, height: size }}
	animationData={animationJson}
/>
```

## 💎 PR Point

<details>
<summary>트러블 슈팅</summary>
1. lottie 파일 문제
그룹 나가기 lottie json 파일의 경우 내부적으로 image파일을 불러와 사용하더군요. 
그래서 디코 design 채널의 파일 공유 스레드에서 json파일 외에 이미지도 다운 받아 public폴더에 넣고, image파일 경로를 살짝 수정하여 적용하니 이미지가 아예 따로 노는 버그가 발생합니다! 이미지를 아예 안 넣으면 404 이미지 아이콘이 표시되구요.

애니메이션을 좀 노려봤더니 이미지 자체가 없으면 이상함 없이 잘 작동할 것 같아 투명 이미지(public/image_0.png, 2KB)를 사용하는 것으로 해결했습니다.
lottie 파일 구조를 잘 몰라서 json에서 image 사용하는 부분을 수정하는 건 포기...
혹시 애니메이션이 원래 제작했던 것과 다르다면 코멘트로 알려주세요.

2. lottie-react 컴포넌트 캡슐화
해당 라이브러리는 react용이라 next.js에서 사용하려면 use client 지시어가 필요합니다.
그에 따라 src/components/shared/animation/Animation.tsx 컴포넌트를 만들고 props를 사용할만한 것으로 추려서 구성했습니다. 컴포넌트 이름은 "Lottie"에 variation을 준 것으로(LottiePlayer 라던지..) 사용할 경우 lottie-react 라이브러리의 내보내기가 검색되는 불편함이 있어 Animation으로 이름 지었습니다.

3. webp
pixel3.gif파일이 22MB로 꽤 크더군요. 그래서 gif보다 용량이 낮고 성능은 좋다고 알려진 webp로 convert(16MB)한 것을 넣어 놨는데, 디자이너분께 우리가 사용할 2개의 gif를 webp 형식으로 다시 만들어 달라고 요청하는 게 나으려나요?

</details>
**사용 방법**
- 컴포넌트로 만든 이유는 트러블 슈팅 2번 참고하세요
```typescript
import { arrow, exitGroup, requireLogin } from "@/assets/lottie";
import Animation from "@/components/shared/animation/Animation";

export default function Home() {
	return (
		<div className="text-purple">
			<Animation size="100px" loop={false} animationJson={exitGroup} />
			<Animation size="100px" animationJson={arrow} />
			<Animation size="100px" animationJson={requireLogin} />
		</div>
	);
}
```

**props** : JSDoc으로도 작성했습니다.
- `size` : 컴포넌트 props 중 하나인 style={ width: xx, height: yy }에 들어갈 값으로 px이나 rem 같은 거 넣어주시면 됩니다.
- `loop` : 무한 반복 재생 여부입니다. `optional`이며 기본값 `true`입니다.
- 'animationJson` : 재생할 lottie json 파일입니다. @/assets/lottie 경로에 있습니다.

## 📸 Screenshot

![Animation](https://github.com/user-attachments/assets/5c498191-f0a7-421a-9870-68e529f0c272)

2024-09-10 16:30 UTC, wuzoo reviewed
짱짱 ! 고생하셨씁니다 ~

2024-09-10 16:30 UTC, wuzoo commented on package.json
>    },
`Lottie`는 디펜던시 말고 `dev` 디펜던시로 넣는게 더 좋아보이는데 어떻게 생각하시나요 ??

2024-09-10 16:30 UTC, wuzoo commented on src/components/shared/animation/Animation.tsx
> +};
`size`에도 마찬가지로 `optional`을 주고 props에 디폴트 값을 설정해주시는 것도 좋아보여요 ! 다른 분들의 의견이 궁금하네용

2024-09-10 16:47 UTC, ptyoiy commented on package.json
>    },
new-sight의 코드 조각처럼 react 컴포넌트로 사용되는 라이브러리라서 `dev`로 가면 안됩니다

2024-09-10 16:50 UTC, wuzoo commented on package.json
>    },
그런가요 ?? 이전에 `Lottie-react` dev로 넣었던 적이 있었는데, 정상적으로 작동했던 것 같습니다. 확인해주실 수 있나요 ? 사실 개발단에서 사용되는 라이브러리이고, 배포할 때 굳이 포함시키지 않아도 될 것 같다는 생각에 `dev`로 넣는 것이 맞다고 생각했습니다 !

2024-09-10 17:14 UTC, ptyoiy commented on package.json
>    },
사실 요즘 프로젝트에서는 `dependency`와 `dev dependency`의 구분이 배포에 있어서 그다지 의미가 있진 않습니다. `dev dependency`에 대표적으로 들어가는 `typescript`나 `번들링 도구`가 빌드 단계에서 필요하기 때문이죠. 
아시다시피 둘 중 하나라도 없으면 빌드 자체가 이뤄지지 못합니다.

그럼 dependency의 구분이 언제 의미 있게 쓰이냐 하면, 아마 `typescript`, `번들링 도구`가 없는 옛날? 백엔드 프로젝트에서 의미 있게 쓰였을 겁니다. `ts`나 `번들링 도구` 없이 `express.js`로 만들어진 프로젝트를 생각해보면 `eslint`같은 `dev dependency`도구가 프로덕션 빌드에 사용되진 않지요. 이 말은 `dev dependency` 도구들이 프로덕션 배포(빌드-배포)에 사용되지 않기 때문에 **dev dependency를 node_modules에 포함 시키지 않아도 된다는 말입니다**. 그리고 이렇게 설치하는 옵션이 바로 `npm install --production`이죠. 근데 요즘 프로젝트에 이 명령어를 사용하여 패키지를 설치했을 때 작동하는 프로젝트는 없을 겁니다 ㅋㅋ

그리고 요청해주신 내용의 경우, `npm install`로 두 `dependency`를 `node_modules`에 설치했으므로 빌드는 잘 이뤄집니다. 하지만 `lottie`를 `dev`에 넣고 `npm install --production`를 사용해서 설치해보면 빌드가 작동하지 않는 것을 확인할 수 있습니다.

2024-09-10 17:19 UTC, ptyoiy commented on src/components/shared/animation/Animation.tsx
> +};
figma를 보면 lottie animation 3개 중 하나는 온보딩 페이지에서 쓰이고, 나머지 둘은 모달창에서 쓰입니다. 일단은 모달창에서 쓰이는 것이 더 많으니 모달 창을 기준으로 디폴트 값을 적용하면 좋겠다는 생각이 드네요. 
여기서 문제는... 제가 아직 모달 창에서 어떤 크기로 사용할 지 모르겠다는 것입니다 ㅎㅎ!
그래서 나중에 모달창 만드실 분이 사이즈 확인해보고 이 캡슐화 컴포넌트의 props를 수정하거나, 
어차피 3개밖에 없으니까 쓸 사람이 알아서 size값을 넣어 사용하는 것이 좋겠다고 생각이 드네요

2024-09-11 04:32 UTC, wuzoo commented on package.json
>    },
저는 사실 그냥 디펜던시, 데브 디펜던시의 차이를 해당 라이브러리가 애플리케이션이 정상적으로 동작하는데 필요하느냐 ! 라는 기준을 가지고 정했었는데요. 실제 런타임에 필요한 녀석이냐를 말이죠

근데 `Lottie` 라이브러리는 당연하게 dev 디펜던시로 생각했는데, 규한님 말처럼 애플리케이션 내에서 사용자에게 애니메이션을 보여주도록 하는 라이브러리이므로 디펜던시에 넣는 것도 좋을 것 같네요 !

동의합니다 ~

2024-09-11 04:32 UTC, wuzoo commented on src/components/shared/animation/Animation.tsx
> +};
좋습니다 !

2024-09-11 04:33 UTC, wuzoo approved these changes

2024-09-11 15:37 UTC, hwangjokim approved these changes
LGTM :D 
webp가 2010년 나온 포맷이고, IE같은 극단적인 케이스가 아니면 지원하니 적극 사용하는것도 좋을 것 같습니다.

---
이건 코드를 떠나 여담으로, 16MB정도나 되는 무시무시한 크기의 파일같은 경우엔 git에 같이 올리고 들고다니기엔 너무 큽니다. 그래서 저희 회사는 100KB 이상 되는 애셋은, `webdav`라는 곳에 올려두고 빌드시 동적으로 받아서 사용합니다. 물론 저희는 깃에 계속 들고다녀야하지만.. 

webdav는 그냥 HTTP 프로토콜을 쓰고, CRUD를 지원하는 클라우드 서버 정도로 생각하시면 편합니다! 
post로 하면 파일 올라가고.. delete로 하면 파일 지워지는 그런 느낌입니다

2024-09-11 15:37 UTC, hwangjokim commented on next.config.mjs
> +
[p1] 로컬에서 빌드용으로 작성하신 내용이신 것 같은데, diff에 잡히지 않도록 main이랑 한번 머지 해주시면 좋을 것 같습니다

2024-09-11 17:09 UTC, j-nary commented on src/components/shared/animation/Animation.tsx
> +};
동의합니다 ~ 사용하는 사람이 수정하겠습니당

2024-09-11 17:10 UTC, j-nary commented on next.config.mjs
> +
제가 했습니다 노티 감사합니다

2024-09-11 17:18 UTC, j-nary requested changes
LGTM!
자세한 PR, 트러블 슈팅 감사합니다.
webp 등 다양한 것들을 알아갈 수 있는 계기가 되었네요.

코리 확인 부탁드립니다 👍 !!

2024-09-11 17:18 UTC, j-nary commented on public/comment.gif
p5) public 폴더 내에 assets 폴더를 하나 더 만들어서 그 안에 파일들 위치시키는 건 어떻게 생각하시나요?

2024-09-11 17:18 UTC, j-nary commented on src/components/shared/animation/Animation.tsx
> +			style={{ width: size, height: size }}
p2) width, height 가 다른 style이 있을 것 같아요! 각각 따로 prop 받는게 좋아보입니다

2024-09-11 17:23 UTC, j-nary commented
+) 추가적으로 assets 세팅에서 백준 레벨 아이콘을 빼먹으셨더라고요! 해당 브랜치에서 그 부분도 쇽샥 작업해서 같이 머지시키면 어떨까~ 생각합니다

2024-09-11 23:11 UTC, ptyoiy commented on public/comment.gif
인정합니다

2024-09-11 23:13 UTC, ptyoiy commented on src/components/shared/animation/Animation.tsx
> +			style={{ width: size, height: size }}
lottie-react로 만들어진 렌더링 결과물을 보시면 svg로 만들어지는데, 셋 다 width, height의 값이 동일합니다. 그래서 width, height를 size로 묶어서 한 것이며, 둘을 따로 작성해도 가로-세로 비율은 동일하고 안에 여백만 생기는 그림이 되어버립니다.
![image](https://github.com/user-attachments/assets/a4eb4e9e-2044-4183-8b68-fdc3892a62e8)

2024-09-11 23:16 UTC, j-nary commented on src/components/shared/animation/Animation.tsx
> +			style={{ width: size, height: size }}
그럼 다른 lottie가 추가될 경우의 확장성은 그때가서 고려해봐도 되겠네용 ~!
확인했습니다 !!

2024-09-11 23:17 UTC, j-nary approved these changes
백준 아이콘 커밋 후 main 브랜치랑 컨플릭잡고 머지해주세요! LGTM!

2024-09-11 23:42 UTC, merged