[ Init ] CD 파이프라인 구축
GAMZA-BAT/algohub-client pull request #24
Opened 2024-09-11 15:21 UTC by hwangjokim

## #️⃣ Related Issue
Closes #4

## ✅ Done Task
  - [ ] CD 파이프라인 구축
  - [ ] CI에도 node modules 캐싱 적용

## ☀️ New-insight

체크아웃전에 캐시 restore 먼저하면 당연하게도 디렉토리가 이동하며 무의미해집니다. ls -al 찍어보기 전까지는 삽질 많이 했네요..ㅎㅎ

## 💎 PR Point

workflows가 젠킨스랑 다르게, 도커 환경을 제가 제어하기 어렵다보니 삽질과 박치기로 테스트를 해야하는게 참 아쉽네요.

추가로, 현재 EC2에 기본적으로 nvm, node, pnpm, pm2가 글로벌로 깔려있다는 가정이 들어간 스크립트입니다. 
사실 이런 외부 의존성이 걸린 경우에는.. 빌드된 아티팩트를 가지고 nvm, node ,pnpm, pm2가 설치된 **도커 이미지를** 만들어서 EC2로 보내고, EC2에서는 그 도커 이미지를 exec해주는 방식으로 가야 환경 변화에 유연해집니다. 이러면 워크플로우와 결합도도 내려가고요.

그런데 당장 리소스도 많지 않고, 시간 더쓰기 싫어서 우선 조금 나이브하게 갑니다 .

지금 ipv4 주소만 있는데, route53에서 도메인 연결하고 말씀 다시 드리겠습니다 :D 

## 📸 Screenshot

2024-09-11 15:24 UTC, hwangjokim commented on .github/workflows/cd-pipeline.yml
> +      - name: Add Github Actions IP to Security group
ec2 VPC에서, ssh 인바운드 모든 IPv4에 대해 열고싶지 않아 (보안상)
해당 권한을 가진 IAM 계정을 파고, 동적으로 추가/제거하도록.

2024-09-11 15:26 UTC, hwangjokim commented on package.json
> +    "start": "next start -p 8080",
기본적으로 3000번대 포트 쓰는데, 배포시에는 8080쓰도록.

참고로 브라우저에서 기본적으로 포트없이 주소만 입력하면 80 포트로 가는데, 이것 다음 명령어로 EC2에서 포트포워딩 해줍니다.
```
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
```

2024-09-11 15:26 UTC, hwangjokim commented on .github/workflows/deploy-dev.yml
리네임입니다.

2024-09-11 16:09 UTC, j-nary requested changes
LGTM !! 코리 부분만 한 번 더 확인해주세요 수고하셨습니다.

2024-09-11 16:09 UTC, j-nary commented on .github/workflows/cd-pipeline.yml
> +      - main
p1) main 브랜치와 배포 브랜치는 분리해서 운영하는 것이 좋을 것 같아요
main 브랜치에서 합의 마친 후에 deploy에 머지하는 방식으로요!
머지할 때 version 같은 것도 명시해주면 배포단위 구분해서 보기도 편할 것 같은데 어떻게 생각하시나요?

2024-09-11 16:20 UTC, hwangjokim commented on .github/workflows/cd-pipeline.yml
> +      - main
.version 파일로 관리하는거 생각하니까 머리아파서 (main branch protection rule..)

그냥 브랜치만 새로 파고, 배포 할 때 마다 깃헙에서 태깅해주는것으로 할까요?

2024-09-11 16:20 UTC, j-nary commented on .github/workflows/cd-pipeline.yml
> +      - main
아 좋습니다!! 배포 버전은 tag로 관리해요 ~

2024-09-11 16:26 UTC, hwangjokim commented on .github/workflows/cd-pipeline.yml
> +      - main
옙 이거 머징시점에 첫 배포 하시죠~

2024-09-11 16:27 UTC, j-nary approved these changes

2024-09-11 23:49 UTC, ptyoiy approved these changes
덕분에 파이프라인에 관해서 많이 배워갑니다.. 고생하셨습니다!

2024-09-14 17:16 UTC, hwangjokim commented
머지하겠습니다.

2024-09-14 17:16 UTC, merged