[ Init ] Biome 설정
GAMZA-BAT/algohub-client pull request #3
Opened 2024-09-07 17:14 UTC by j-nary

## #️⃣ Related Issue
Closes #1 

## ✅ Done Task
  - [x] Biome 설치
  - [x] Biome 설정 파일 추가

## ☀️ New-insight

### Biome이란?

- 새로나온 ESLint + Prettier 를 대체하는 lint 라이브러리
    
    [[Biome: 차세대 JS Linter와 Formatter](https://teamdable.github.io/techblog/biome-js-linter-and-formatter)](https://teamdable.github.io/techblog/biome-js-linter-and-formatter)
    
- 공식 사이트 왈: “One toolxhain for your web project”

### 왜 Biome일까?

- Prettier보다 빠른 성능
    
    <img width="288" alt="image" src="https://github.com/user-attachments/assets/01de3a43-5d41-4599-997c-61aedc130206">
    
- ESLint + Prettier 처럼 별도의 도구를 함께 사용하는 것보다 간단한 설정

→ 단점은 레퍼런스가 부족하다는 것 정도?
### Biome 설정 방법

- biome 설치
    
    ```bash
    pnpm add -D @biomejs/biome
    pnpm add --save-dev --save-exact @biomejs/biome
    ```
    
- `biome.json` 파일 생성
    
    ```bash
    pnpm biome init
    ```
    
    - 포매터: Prettier의 모든 구성 옵션 구현 → 완전한 호환성
    
    ```json
    {
    	"$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
    	"organizeImports": {
    		"enabled": true  // 불필요한 import를 제거하고, import 구문을 자동으로 정리함
    	},
    	"linter": {
    		"enabled": true,  // 린트 기능 활성화
    		"ignore": ["node_modules"],  // "node_modules" 폴더는 린트 검사에서 제외
    		"rules": {
    			"all": true,  // 모든 린트 규칙 활성화
    			"complexity": {
    				"noUselessFragments": "off",  // 불필요한 JSX fragments를 금지하는 규칙 비활성화
    				"noExcessiveCognitiveComplexity": "off"  // 코드의 복잡성을 지나치게 높이지 않도록 하는 규칙 비활성화
    			},
    			"style": {
    				"useSingleVarDeclarator": "off",  // 하나의 `var`, `let`, `const` 선언문에서 변수를 한 개씩 선언하는 규칙 비활성화
    				"noParameterAssign": "off",  // 함수 파라미터에 직접 값을 할당하는 것을 금지하는 규칙 비활성화
    				"noNonNullAssertion": "off",  // `!` 연산자를 사용하여 값이 null이 아님을 확정하는 구문을 금지하는 규칙 비활성화
    				"useNamingConvention": "off",  // 변수와 함수의 명명 규칙을 강제하는 규칙 비활성화
    				"useFilenamingConvention": "off",  // 파일 명명 규칙을 강제하는 규칙 비활성화
    				"useBlockStatements": "off",  // 단일 구문을 위한 중괄호 사용을 강제하는 규칙 비활성화
    				"noDefaultExport": "off",  // default export를 금지하는 규칙 비활성화
    				"noImplicitBoolean": "off"  // 불리언 값이 암묵적으로 사용되는 것을 금지하는 규칙 비활성화
    			},
    			"suspicious": {
    				"noExplicitAny": "off",  // TypeScript의 `any` 타입 명시를 금지하는 규칙 비활성dexKey": "off",  // 배열의 인덱스를 key로 사용하는 것을 금지하는 규칙 비활성화 (React에서 주로 사용)
    				"noEmptyBlockStatements": "off",  // 빈 중괄호 블록을 금지하는 규칙 비활성화
    				"noConsoleLog": "off",  // `console.log` 사용을 금지하는 규칙 비활성화
    				"useAwait": "off"  // Promise 반환 함수에서 `await` 사용을 강제하는 규칙 비활성화
    			},
    			"correctness": {
    				"useExhaustiveDependencies": "off"  // React의 `useEffect` hook에서 모든 의존성을 명시하는 것을 강제하는 규칙 비활성화
    			},
    			"performance": {
    				"noAccumulatingSpread": "off"  // 배열 또는 객체의 스프레드 연산을 사용하여 누적되는 작업을 금지하는 규칙 비활성화
    			},
    			"nursery": {
    				"all": false  // 실험적인 린트 규칙 비활성화
    			}
    		}
    	},
    	"formatter": {
    		"enabled": true,  // 코드 포매터 활성화
    		"lineWidth": 80,  // 한 줄에 허용되는 최대 문자 수 설정 (80자)
    		"indentWidth": 2  // 들여쓰기 너비 설정 (2칸)
    	},
    	"files": {
    		"include": [
    			"**/*.ts",
    			"**/*.tsx",
    			"**/*.js",
    			"**/*.jsx"
    		]
    	}
    }
    ```
    
    - prettier 완벽 호환된다해놓고 막상 prettier 규칙 쓰면 그런 속성없대 아래 코드 참조함!
        
        https://github.com/OneOfOne/dotfiles/blob/master/biome.json
        
- biome 직접 실행
    
    ```bash
    pnpm biome lint
    ```
## 💎 PR Point

- 추가하고 싶은 규칙이 있다면 언제든 코리로 남겨주세요!

## 📸 Screenshot

2024-09-07 19:29 UTC, hwangjokim requested changes
고생하셨습니다~ 코멘트 확인 부탁드립니다.
개발 단계에서 놓치지 않기 위해서는, vscode에서 `biome` extension을 깔아야 IDE 코드라인에서 제대로 경고를 띄워주는 것 같아요.

2024-09-07 19:29 UTC, hwangjokim commented on biome.json
> +			"node_modules"
[p5] "static", ".next"도 ignore 해야할것같아요. 지금 세팅으로는 번들링된 파일같은것도 다 검사하네요

2024-09-07 19:29 UTC, hwangjokim commented on biome.json
> +		"rules": {
궁금한것인데 비활성화한 옵션들은 어떤 기준으로 비활성화 하신건가요? 
추가로 현재 옵션으로는 `layout.tsx`에서 lint에 실패하는데, CI/CD 파이프라인 붙으면 메인 브랜치에서 빌드가 실패할거라서 셋업 하는김에 고쳐서 같이 올라가면 좋을 것 같아요.

2024-09-08 08:02 UTC, wuzoo reviewed
LGTM ~ biome 좋네요

2024-09-08 08:02 UTC, wuzoo commented on biome.json
p3)
1. biome으로 저희가 기존에 eslint나 prettier로 하는 import order 맞추는 것도 설정해주면 좋을 것 같아요. 안중요할 수도 있지만 해놓으면 확실히 import 구문들이 깔끔해지더라고요
2. eslint에는 arrow function을 강제하는 속성이 있는데, 그것도 추가하면 좋을 것 같아요. 저희의 컨벤션 중 하나이니까요 !

추가적으로 개발자의 취향인 부분들 다른 팀원들과 좀 의논해서 정하면 좋을 것 같습니다.

2024-09-08 08:54 UTC, ptyoiy commented on biome.json
1번은 organizeImports 속성으로 적용되는데 이미 쓰고 있네요.
2번은 complexity에서 "useArrowFunction"를 사용하면 돼요.

저는 lint나 포맷팅 기능 따로 세팅 안하고 기본으로 써오다가 얼마전에 엄격한 거 설치해서(airbnb) 써봤는데, 온갖 걸 off했던 기억이 나네요. 다른 분들 어떤 속성 좋아하시는지 구경하고 싶은데 다음 주 회의 안건으로 넣어 놓을게요

2024-09-09 08:19 UTC, wuzoo commented on biome.json
좋습니다 !!

2024-09-09 09:11 UTC, j-nary commented on biome.json
> +			"node_modules"
앗 네 !! 감사합니다 :)

2024-09-09 09:13 UTC, j-nary commented on biome.json
> +		"rules": {
어떤 부분을 고쳐야한다는 말일까용 ...?

2024-09-09 09:14 UTC, hwangjokim commented on biome.json
> +		"rules": {
현재 상태에서 위에 ignore들 추가하고, 
pnpm biome lint
하면 fail나용

2024-09-09 09:14 UTC, j-nary commented on biome.json
반영완료했습니다! 감사합니다:)

2024-09-09 09:22 UTC, ptyoiy approved these changes

2024-09-09 09:25 UTC, j-nary commented on biome.json
> +		"rules": {
고쳤습니당 ! 이제 fail이 나지 않아용! 피드백 감사합니다 :)

2024-09-09 09:26 UTC, hwangjokim approved these changes
수고하셨습니다~!

2024-09-09 10:01 UTC, merged