feat: Add common-input component
GAMZA-BAT/algohub-client pull request #38
Opened 2024-09-17 16:31 UTC by hwangjokim

## #️⃣ Related Issue
Closes #5 

## ✅ Done Task
  - [ ] 컴포넌트 구현

## ☀️ New-insight

보통 파일시스템급 로우레벨이나 컴포넌트랑 관련없는 로직레벨을 많이 다뤘습니다.
뷰 레벨 작업 거의 안해봐서 공통 컴포넌트 처음 만들어보는데요, html css 하는 느낌이라 바닐라 익스트랙트에서 뭐 쓸 수 있는지 정도만 알아갔습니다.

## 💎 PR Point

사실 지식도 적고 여유시간이 많지 않아 조금 급하게 구현하고, PR에서 맞으면서 고치자는 느낌으로 만들었습니다. 
저는 figma 명시된 값 정확히 쓴다보다는, 같게 보이면 된다 주의여서 몇가지 값들은 figma랑 조금 다를 수 있습니다.  
기본적으로 textarea를 쓰도록 했고, white-space 유무로 input / textarea 나누도록 해봤습니다.
피드백 미리 감사드립니다. 피드백은 빠르게 반영해보겠습니다. 

## 📸 Screenshot

https://github.com/user-attachments/assets/cf5b98e4-c6c5-4e06-8b38-c35479576e22

2024-09-17 16:31 UTC, hwangjokim commented on src/styles/themes.css.ts
포매터만 먹였습니다.

2024-09-18 07:25 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +import { useState } from "react";
클라이언트 전용 함수들(react hook, event handler)이 들어있으니 "use client" 추가해주세요!

2024-09-18 07:25 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +}
type은 `extends TextareaHTMLAttributes<HTMLTextAreaElement>` 이걸 추가해주세요.
이러면 `placeholder`, `defaultValue`를 props에서 지워도 되며 사용하는 개발자가 원하는 속성들을 적용할 수 있어 좋습니다. 예시로 Button 컴포넌트의 ...props 부분 참고하시면 될 듯 합니다.

2024-09-18 07:26 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +}
`size` prop에 `textarea`도 선택 가능한 게 몬가 몬가 하네요..
개인적인 생각으로는 `size`에서 `textarea`를 뺀 뒤, `medium`이 기본값인 optional prop으로 바꾸고
`mode` prop을 추가해서 기본 값 `input`, `textarea`를 선택하게 하면 어떨까 싶어요!

2024-09-18 07:28 UTC, ptyoiy commented
구현하시느라 고생 많으셨습니다! 잘 구현 하신 것 같아요.
제 수정 사항이 반영되면 어푸하겠슴다

2024-09-18 07:46 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +}
size prop 이야기 조금 고민해보았는데요,

mode prop이 추가되어 input, textarea 를 구분자로 갖고
size props에 medium, large를 둘 경우

input + medium, large엔 문제가 없습니다.
다만 textarea는 size prop을 무엇을 주더라도 무시..가 될 것 같습니다.
이게 조금 어색해서 textarea도 medium, large에 따라 크기가 달라지게 하면 현재 디자인 시안상 없는 것 까지 만들어지게 되어 불필요하다고 느껴지기도 하는데 조금 더 설명해 주실 수 있을까요? 

그냥 size가 아니라 이름을 type같은걸로 바꿀까 싶기도 하네요

2024-09-18 07:53 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +}
textarea에 그런 문제가 있군요. 확실히 type으로 바꾸면 좋을 것 같은게 이미 컴포넌트 이름이 Input 이니까 `medium`, `large` 외에 `textarea`를 고르면 이걸로 동작하는구나 하고 인식하기 좋을 것 같아요. 다른 분들은 어떻게 생각하실지 궁금하네요

2024-09-18 13:51 UTC, j-nary requested changes
수고하셨습니당! 코리 확인 한 번 부탁드려용 :)

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.tsx
> +  error?: boolean;
boolean 값이니 속성 네이밍 컨벤션대로 `isError` 로 변경해주세용!

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.tsx
> +  const [active, setActive] = useState<boolean>(false);
마찬가지로 boolean 값이니 `isActive` `setIsActive` 변경 부탁드립니당 :)

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.css.ts
> +        ":hover": {
true일때와 hover일 때 차이가 없는 것 아닌가욤 ?
hover의 기본 동작을 끄고 싶은 의도라면 reset에서 textarea의 default style을 꺼주는게 좋을 것 같아요!
아래 error나 compoundVariants 에서도 똑같이용!

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.css.ts
> +        fontSize: "1.4rem",
`fontSize` 랑 `lineHeight` 관련된 건 `theme` 에서 가져오면 좋을 것 같아요!
아래 사진에 표시된 부분대로 theme 설정해두었습니당!
혹시 theme.font 를 활용하지 않으신 특별한 이유가 있으실까요?

<img width="334" alt="image" src="https://github.com/user-attachments/assets/e42cdad3-9a06-4a3e-8a86-5385805ddc9b">

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.tsx
> +}
`placeholder` `defaultValue` 에 추가로 `handleChange` 도 인터페이스에 없어도 될 것 같아용! 상속해온다면!

2024-09-18 13:51 UTC, j-nary commented on src/common/component/Input/index.tsx
> +}
size로 `medium` `large` 두고 `variant`로 `input` `textarea` 두는 것도 좋지만,
input이랑 textarea 컴포넌트를 아예 분리하는 것도 좋아보여요!
common인 만큼 어떤 변경사항이 생길 지 모르니 성격이 아예 다른 컴포넌트는 분리하는 것이 좋아보입니당

2024-09-18 14:02 UTC, wuzoo reviewed
고생하셨습니다 ~ 🚀🚀🚀

2024-09-18 14:02 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +}
저는 `Input`이랑 `Textarea` 컴포넌트 따로 만드는 것도 좋은 것 같아요 !!
굳이 Input 컴포넌트 하나에서 둘 다 해결하려고 하지 않아도 될 것 같습니다 ..

2024-09-18 14:02 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +  error?: boolean;
규한님 말씀처럼 공통 컴포넌트인 만큼 조금 확장성을 더 고려한다면 상속도 고려해볼 수 있을 것 같아요. `onChange`, `placeholder` 등등 기본적인 input의 프로퍼티들은 모두 생략해줄 수 있을 것 같습니다.

2024-09-18 14:02 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +    </div>
저는 보통 `Input` 컴포넌트 만들 때 해당 컴포넌트 안에 `label`과 인풋 아래로 나오는 `text` 요소를 함께 만들어주는 편이에요 !
거의 모든 GUI가 인풋은 어떤 인풋이지에 대한 `label`과 입력이 잘못되었을 경우 나타나는 `supportingText`로 함께 구성되어있기 때문입니다.

이렇게 인풋에서 `isError` 혹은 특정 상태일 때 `text`를 띄워주게 하고, 어떤 인풋인지에 대한 `label`도 함께 보여준다면 재사용성도 증가하고, 사용자 입장에서 사용하기도 편할 것 같아요

2024-09-18 14:02 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +        }}
스타일 코드 안에서 선택자를 통해서 제어할 수 있지 않나요 ??

2024-09-18 16:23 UTC, hwangjokim commented on src/common/component/Input/index.css.ts
> +        fontSize: "1.4rem",
있는걸 몰랐습니다 ^_________^

2024-09-18 16:28 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +  error?: boolean;
onChange는 dx를 위해.. 이벤트를 받기보다 직관적으로 string을 받아 처리 할 수 있게 한번 래핑한것이라 의도긴 합니다!
나머지는 상속으로 반영했습니다 :)

2024-09-18 16:32 UTC, hwangjokim commented on src/common/component/Input/index.css.ts
> +        ":hover": {
> hover의 기본 동작을 끄고 싶은 의도

가 맞고, 어떤 취지의 코멘트인지도 아주 잘 이해했습니다.
그러나 `reset`에서 끈다는것을 이해하지 못 했습니다..

2024-09-18 17:02 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +        }}
넵. bar까지는 선택자를 가지고 이리저리 해볼 수 있는데, 부모의 border를 input focus 여부로 다르게 해야하는데
부모에서 자식 참조가 불가능한것으로 알고 있어 이렇게 두었습니다.
혹시 제가 모르는 대안이 있을까요?

2024-09-18 17:04 UTC, hwangjokim commented
코멘트 내일중으로 모두 반영 할 수 있도록 해보겠습니다~~

2024-09-19 07:32 UTC, j-nary commented on src/common/component/Input/index.css.ts
> +        ":hover": {
<img width="449" alt="image" src="https://github.com/user-attachments/assets/6cd3f1e3-7100-46a3-be9a-9534635b041d">

여기서 hover 시에 textDecoration을 꺼주시면 될 것 같아용 !!

2024-09-19 15:25 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +        }}
자답) focus-within 이란게 있어서 그것으로 해결했습니다.

2024-09-19 15:27 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +    </div>
좋은 피드백 감사합니다.
label같은 경우는 시안상으로도 다양한 크기를 가질 수 있는 듯 합니다. label은 이에 대한 커스터마이즈를 지원해야 할 것 같은데요, 스타일을 넘겨주는 방법도 모호하다고 느껴지고, 그렇다고 직접 Label 컴포넌트를 만들어 넘겨주는것도 조금 어색하다고 생각됩니다. 따라서 label은 구현자 입장에서 알아서 만들어 쓰는게 낫지 않을까란 생각이 들기도 합니다. 어떻게 생각하시나요?

2024-09-21 16:56 UTC, hwangjokim commented
아직 질문을 남겨둔 label 제외하고 코멘트들 반영했습니다.

2024-09-21 16:57 UTC, hwangjokim commented on src/styles/themes.css.ts
> +    error: "#ff3c53",
실제로 추가한건 이것이고, 저장하면서 포매터 먹어서 diff로 잡혔습니다.

2024-09-21 17:02 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +  extends Omit<InputHTMLAttributes<HTMLInputElement>, "size"> {
input태그에 기본적으로 있는 size는 width 제한용인데, 저희가 쓸 컴포넌트에선 필요없어서 제거했습니다.
제거 안하면 중복이라 타입오류가 발생해서..

2024-09-22 08:21 UTC, j-nary requested changes
LGTM !!
Textarea, Input 에 들어간 커스텀 커서 때문에 placeholder가 깜빡 거려서 디자이너 분한테 커스텀 커서 없애달라고 요청 드렸습니당! 
개선하는 리소스에 비해 불필요한 기능이어보여서용!
그 부분 없애주시면 감사할 것 같습니당 코리 몇 개 확인해주세요 :)

2024-09-22 08:21 UTC, j-nary commented on src/common/component/Textarea/index.tsx
> +      </div>
<img width="656" alt="image" src="https://github.com/user-attachments/assets/bf785733-4f3c-408c-9bab-2569ede09936">
요 에러 컴포넌트 분리하는건 어떻게 생각하시나요?
`ErrorText` 로 분리해도 좋을 것 같아요!
Error 메세지 UI가 저걸로 통일될 거라고 하시네요!

2024-09-22 08:25 UTC, wuzoo reviewed
바쁘신데 정말 고생 많으십니다 황조님 !! ㅠㅠ 회사일 때문에 작업이 늦쳐지는거 전혀 안미안하셔두 대고 나중에는 특정 태스크 차지하는 것보다 코리 위주로 하셔도 괜찮을 것 같아요 !

2024-09-22 08:25 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +}
스토리북 상으로 인풋값을 입력할 때 `placeholder` 칸이 움직이는 것처럼 보이는데, 좀 UX적으로 좋지 않을 수도 있을 것 같아요 !

2024-09-22 08:25 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +    </div>
라벨 역할을 하는 라벨이라는 요소가 인풋 없이 띄워질 상황이 없다고 느껴지기 때문에, 저는 `Input` 컴포넌트에서 작성해주는 것이 맞다고 생각합니다 !!

인풋이 `error`일 경우에는 `label`에도 에러 텍스트를 표시해주어야 하니 인풋에서 받은 `isError`를 같이 라벨에도 처리하면 사용하기 손쉬울 것 같아요 ! 또한 디자인상으로는 라벨 크기가 하나인 것 같은데 잘못 본 것인지는 모르겠습니다. 만약 사이즈가 일부 다양하더라도 인풋에서 받은 `size` prop으로 라벨에도 같이 넘겨주어 처리하게 해준다면 될 것 같아요 !

2024-09-22 08:25 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +}
추가적으로 `Input`의 현재 JSX 구조를 좀 더 단순화할 수 있을 것 같아요. 특히 `icon` 렌더링하는 부분에서 `div`로 한 번 더 감싸주지 않아도 되지 않을까 하는 생각이 듭니다.. !

아 ! 그리고 진님 코리에서 발견한건데, 커서 `bar` 컴포넌트가 사라진걸로 확인되므로 구조 좀 더 단순화 가능할 것 같슴니다 !!

2024-09-22 11:06 UTC, hwangjokim commented on src/common/component/Textarea/index.tsx
> +      </div>
옙 좋습니다~

2024-09-22 12:31 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +    </div>
@wuzoo  주용님께서 말씀하고 계신 인풋의 `label`이 어떻게 생긴것을 말씀하시는건지 궁금합니다..! 이 부분 싱크가 안맞고 있는 것 같아서, 수정 전 확인하고싶습니당

2024-09-22 12:40 UTC, hwangjokim commented on src/common/component/Input/index.tsx
> +}
div 감싸는것 이야기가 다음 코드에서 fragment 넣은 것 말씀이실까요?
```typescript
    <div className={errorWrapper}>
      {isError && (
        <>
          <IcnError className={errorIconStyle} />
          <div className={errorMsgStyle}>{errorMsg}</div>
        </>
      )}
    </div>
```

맞다면 Syntax상 필수적인 부분이라 넣은것이긴 한데 다른 부분을 말씀하신걸까요?

2024-09-23 11:40 UTC, ptyoiy approved these changes
다른 분들의 무수한 리뷰로 인해 굉장히 발전해 버렸군요.. 제가 login, join 페이지 만들 때 필요한 부분들을 좀 체크 해봤는데, 아무 문제 없을 것 같네요 !
바쁘신 와중에 고생 많으셨습니다

2024-09-23 17:14 UTC, j-nary requested changes
input이 진짜 제일 할 게 많네요 ㅜㅜ 코리 한 번 더 확인 부탁드립니당 :)

2024-09-23 17:14 UTC, j-nary commented on src/common/component/ErrorInfo/index.tsx
> +          <IcnError className={errorIconStyle} />
<img width="427" alt="image" src="https://github.com/user-attachments/assets/649371d9-3f31-417c-941c-d51676a8d3f6">

요 아이는 Icon이 없네용!
variant로 Icon 여부 prop으로 받아도 좋을 것 같아요!

2024-09-23 17:14 UTC, j-nary commented on src/common/component/Input/index.css.ts
> +    borderRadius: "0.5rem",
border 관련 속성은 `px` 로 통일하는 것에 대해 어떻게 생각하시나요?

2024-09-23 17:14 UTC, j-nary commented on src/common/component/ErrorInfo/index.tsx
> +          <IcnError className={errorIconStyle} />
<img width="649" alt="image" src="https://github.com/user-attachments/assets/c5acd40b-8caf-4858-b26b-6a1ddaae335b">

icon이 있는 건 `0.2rem`, icon이 없는 건 `0.4rem`이니까
icon이 없을 때 `padding: 0.2rem 0` 추가해주면 좋을 것 같아요!

2024-09-23 17:14 UTC, j-nary commented on src/common/component/Input/index.tsx
> +      </div>
input 태그 하나로 합쳐질 수 있을 것 같아요! padding으로 크기 조정하고!

2024-09-23 17:14 UTC, j-nary commented on src/common/component/Textarea/index.tsx
> +      </div>
이 아이도 마찬가지로 textarea 하나로 합쳐질 수 있을 것 같아요!
이렇게 분리시킨 이유가 따로 있을까용?

2024-09-23 17:14 UTC, j-nary commented on src/common/component/Textarea/index.css.ts
> +    boxSizing: "border-box",
요 아이 글로벌 스타일로 지정되어있어서 지워주셔도 될 것 같아요!

2024-09-24 00:25 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +const Input = ({
로그인, 회원 가입 페이지에서 사용하려고 보니 두 가지 수정 요청 사항이 생겼습니다...

1. `ref`로 input의 값을 관리하는 uncontrolled 방식으로 쓰고 싶었는데 `ref`가 없어서 안되네요. `forwardRef` 적용 및 `onChange` props 삭제 부탁 드립니다. 

2. `isError`에 따라 에러 메세지가 나오는데, 로그인 페이지의 경우 id, pw의 유효성 검사를 통과하지 못했을 때 `id` input에만 에러 메세지가 나오게 해야 되더라구요. `isError`로 메세지 없이 빨강 테두리만 입히고 싶은데, 메세지 표시 여부는 따로 받도록 변경 부탁 드립니다.

2024-09-24 06:21 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +    </div>
제가 말한 `label`은
<img width="317" alt="image" src="https://github.com/user-attachments/assets/204a7c3c-914d-4731-89c1-1e6d8ef06036">

이거 였는데, 실제로 `label`이 없는 인풋들도 많네요 .. ? 근데 사실 `label`을 prop으로 넘겨준다면 당연히 `label`이 있을 때만 라벨 컴포넌트를 조건부로 렌더링하게 처리하는게 맞다고 생각해서, 이건 문제가 안될 듯 싶어요.

저는 라벨 컴포넌트를 항상 인풋에서 `prop`으로 넘겨 함께 사용하는 것이 편하다고 생각해왔었는데, 이 부분에서 황조님과 진님의 의견도 궁금하네요 ,.. !

2024-09-24 06:25 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +  handleChange: (value: string) => void;
`handleChange` prop도 상속을 통해 받은 프롭들을 `spread`로 `input` 요소에 넘겨준다면 지워주어도 될 것 같습니다 !

2024-09-24 06:25 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +      <ErrorInfo isError={isError} errorMsg={errorMsg} />
사실 밑에 보여지는 `text`의 경우 `error`가 아닌 경우들도 있는 것 같아요..!

<img width="479" alt="image" src="https://github.com/user-attachments/assets/a698a5ca-48d7-4ae9-a97d-69fbda025318">

그냥 `SupportingText`라는 컴포넌트를 만들고 해당 컴포넌트에 `text`를 넘겨주되 `isError`도 받게 해서 해당 컴포넌트에서 에러 시의 인터랙션을 처리하도록 하면 될 것 같슴니다 !

2024-09-24 18:32 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +      <ErrorInfo isError={isError} errorMsg={errorMsg} />
위에 제 두 가지 요청 사항 중 두 번째 얘기의 연장선이 되겠네요. 제 생각에도 `ErrorInfo` 컴포넌트를 Input, textarea에서 아예 분리하고 `SupportingText` 같은 걸로(보통은 Description이라 이름 짓네요) 이름을 변경한 뒤, 필요한 props를 추가하면 좋겠습니다!

2024-09-24 18:45 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +    </div>
제가 로그인/회원가입 페이지를 만들면서 공통 컴포넌트로 `Form`을 만들고 있습니다. `react-hook-form`과 `zod`를 사용해서 구성 중인데, 이 `Form` 컴포넌트는 `react-hook-form`의 기능들을 적용하면서 자동으로 `form field`의 여러 요소(input위 라벨, 아래 설명, input 자체)에 aria 속성들을 붙여줄 수 있습니다. 

label의 경우에는 주용님 말씀대로 input 없이 label이 띄워질 일이 없으니 `Form` 컴포넌트를 만드는 김에 `Label`도 제가 만들어서 로그인 페이지 PR에 설명 및 스토리로 사용 방법을 정리해 놓겠습니다.

2024-09-28 11:01 UTC, hwangjo-v6x commented on src/common/component/Input/index.tsx
> +  handleChange: (value: string) => void;
이것 위에서도 같은 코멘트 받았는데, 상속한다면 event를 받아야해서 개발 편의상 바로 string 받아 쓸 수 있도록 의도한 부분입니다

2024-09-28 13:27 UTC, hwangjokim commented on src/common/component/Textarea/index.tsx
> +      </div>
원래 bar 있던 시절에 작성했던거라, 필요 없어서 반영하겠습니다~

2024-09-28 13:32 UTC, hwangjokim commented
반영이 늦어 죄송합니다 (__) 
label 규한님께서 form에서 하신다고 하셔서, 그 부분 제외 반영했습니다.

2024-09-29 11:59 UTC, hwangjokim commented
@ptyoiy 님, `supportingText` 분리작업 했습니다.

2024-09-30 19:30 UTC, j-nary approved these changes
LGTM 너무 고생하셨습니당 
Input 만만치 않은 공컴이었네오 .. 덕분에 코드 보고 많이 배워갑니당 👍🚀

2024-10-01 19:10 UTC, ptyoiy commented
Form 공통 컴포넌트에서 사용하다 보니 아주 사소한 추가 수정 사항이 생겼는데(ref, className), 간단한 작업이니 이건 Form 브랜치에서 제가 적용하겠습니다. 수정 사항은 #54 에 작성해 놓을게요!
정말 고생 많으셨어요!👍🚀

2024-10-03 11:32 UTC, hwangjokim commented
@wuzoo 이거 더 코멘트 주실 것 있으실까요??

2024-10-03 12:00 UTC, wuzoo approved these changes
정말 정말 고생하셨습니다 ~!@!! 🚀

2024-10-03 12:04 UTC, merged