[ Feat ] alarm list component 구현
GAMZA-BAT/algohub-client pull request #41
Opened 2024-09-18 12:35 UTC by ptyoiy

## #️⃣ Related Issue
Closes #40 

## ✅ Done Task
  - [ ] 알림 리스트 컴포넌트 구현
  - [ ] 스크롤 바 커스터마이징
  - [ ] 테스트 데이터 적용 후 확인
  - [ ] 접근성 관련 속성 적용

## ☀️ New-insight

1. 접근성 기능 구현
`div` 등 클릭 이벤트가 원래 없는 태그에 이벤트를 부착할 때 스크린 리더도 선택할 수 있게 `keydown` 이벤트도 
추가해 보았습니다. 이 때 사용될 `enter`, `spacebar`를 감지하는 `keydown` 이벤트 핸들러는 `util/dom.ts`에 추가했습니다.

2. 이벤트 버블링에 의한 `keydown` 가로채기 방지
부모 `div`에 `keydown` 이벤트 핸들러가 부착돼 있으면 자식 요소에 `focus`-`keydown`을 통한 클릭을 해도 부모 `div`가 가로채는 버그가 발생합니다. 해결을 위해 `handleStopPropagationKeyDown()`을 사용했습니다. 자세한건 `util/dom.ts`에서 JSDoc을 확인해 주세요.

3. 스크롤 바 커스터마이징
```typescript
  // css.ts
  height: "24.5rem",
  overflowY: "scroll",

  selectors: {
    // 스크롤바 너비 설정
    "&::-webkit-scrollbar": {
      width: "0.3rem", // 세로 스크롤바의 너비를 0.3rem로 설정
    },
    // 스크롤바 thumb (스크롤바의 움직이는 부분) 스타일링
    "&::-webkit-scrollbar-thumb": {
      background: theme.color.mg1, // 스크롤 thumb의 배경색 설정
      borderRadius: "0.4rem", // 스크롤 thumb의 모서리를 둥글게 설정
    },
    // 스크롤바의 위아래 버튼 영역 크기 설정
    "&::-webkit-scrollbar-button": {
      height: "1rem",
    },
    // 스크롤바 thumb가 활성화(클릭 중)일 때 스타일 변경
    "&::-webkit-scrollbar-thumb:active": {
      background: theme.color.mg4,
    },
    // 스크롤 트랙(스크롤바의 배경) 스타일링
    "&::-webkit-scrollbar-track": {
      background: "transparent", // 스크롤 트랙을 투명하게 설정
      boxShadow: "none", // 트랙에 그림자를 없앰
    },
  },
});
```

## 💎 PR Point

- 알림 리스트 컴포넌트 트리
```bash
Header
│ ... 
├── Notification
 │     ├── Notification.TriggerIcon
 │     └── AlarmListItem[] (map 순회 생성)
 │            ├── Profile Image
 │            ├── Name
 │            ├── Message
 │            ├── Date
 │            └── Delete Button (active 시 표시)
```

## 📸 Screenshot

![Animation2](https://github.com/user-attachments/assets/743435eb-6399-4a23-bc8b-555c74a2b973)

2024-09-18 14:12 UTC, j-nary requested changes
세심한 부분까지 꼼꼼하게 신경쓰신 코드가 돋보이네요!
코리 드린 것 확인 부탁드립니당 수고하셨슴당 !!

2024-09-18 14:12 UTC, j-nary commented on src/common/component/AlarmListItem/index.tsx
> +  };
간단한 handle 함수는 inline으로 처리해주시는 게 어떠신가용?

2024-09-18 14:12 UTC, j-nary commented on src/shared/component/Header/Notification.tsx
>  const Notification = () => {
`Notice`는 공지게시판을 뜻하는 네이밍이어서 (그룹게시판에 있는)
Header에 있는 알람은 `Alarm`으로 재명명하는 건 어떻게 생각하시나요?
그룹 공지게시판과 혼선이 생길 수도 있을 것 같아서요!

2024-09-18 14:12 UTC, j-nary commented on src/shared/component/Header/Notification.tsx
> +            key={index}
map에서 key값으로 index를 받는 것은 권장하지 않습니다
이미 의도하신 걸 수도 있겠지만!
후에 api 연결 후에 key값을 고유 id 속성으로 변경하시는게 좋을 것 같아요!

2024-09-18 14:12 UTC, j-nary commented on src/shared/component/Header/Notification.css.ts
> +export const ulStyle = style({
어떤 부분 때문에 UI와 다르게 나오는 건지 정확하게 파악은 못했지만, list나 그것을 감싸는 wrapper의 padding값이 다른 것 같아요!
`숭실대학교 알고리즘` 까지 한 줄에 나오도록 수정 부탁드립니당! 지금 wrapper에 비해 내용물이 다소 큰 감이 있네용

<img width="779" alt="image" src="https://github.com/user-attachments/assets/78b20033-dd12-4c31-ac92-1d5c301e98b7">

2024-09-18 14:12 UTC, j-nary commented on src/common/util/dom.ts
> + */
불필요한 주석이면 삭제 부탁드립니당!

2024-09-18 14:12 UTC, j-nary commented on src/common/component/AlarmListItem/index.tsx
해당 AlarmList는 Header에서만 쓰이는 컴포넌트 아닌가용?
`common` 보다는 `shared/component/Header` 에 위치시키는게 맞아보입니당!
다른 분들의 의견도 궁금하네요 :)

2024-09-18 14:12 UTC, j-nary commented on src/common/component/AlarmListItem/index.tsx
> +  handleClick: () => void;
div 요소 상속받는 건 어떻게 생각하시나요?
handleClick을 인터페이스에 명시해둘 필요 없어보입니당!

2024-09-18 14:12 UTC, j-nary commented on src/common/component/AlarmListItem/index.tsx
> +          className={deleteButtonStyle({ active: isActive })}
보아하니 active 를 recipe variant 속성으로 추가하는 것보다 button의 disabled 속성을 활용하는 것이 좋아보이는데 어떻게 생각하시나용?

2024-09-18 14:13 UTC, wuzoo reviewed
고생하셨습니다 !!

2024-09-18 14:13 UTC, wuzoo commented on src/common/component/AlarmListItem/index.css.ts
> +  listStyle: "none",
요거 글로벌 스타일로 처리되어있지 않나요 ? 아니라면 글로벌 스타일에 추가해도 좋을 것 같아요

2024-09-18 14:13 UTC, wuzoo commented on src/common/component/AlarmListItem/index.tsx
> +        onMouseOut={handleMouseOut}
이거 스타일 코드에서 선택자로 구현 못하나요 ??

2024-09-18 14:13 UTC, wuzoo commented on src/common/component/AlarmListItem/index.tsx
> +        onMouseOut={handleMouseOut}
지금 스크린 리더가 느끼기엔 버튼 안에 버튼이 있어서 수정이 조금 필요할 것 같아요 !

2024-09-18 14:13 UTC, wuzoo commented on src/common/component/AlarmListItem/index.tsx
> +        </button>
불필요한 JSX 요소의 중첩이라고 느껴지는데 이미지 하나만 써도 되지 않을까요 ?

2024-09-18 14:13 UTC, wuzoo commented on src/common/component/AlarmListItem/index.tsx
> +  handleClick: () => void;
네이밍 `onClick`이 맞는 것 같슴니다 !

2024-09-18 14:13 UTC, wuzoo commented on src/shared/component/Header/Notification.tsx
> +      <ul className={ulStyle} role="list" aria-label="알림 목록" tabIndex={undefined}>
`tabIndex`에 `undefined`는 어떤 의도로 사용하신건가요 !! 탭으로 포커스되지 못하게 하려는 의도라면`-1`이 맞는 것 같습니다 !
또한 `ul` 태그에 `role=list`는 중복적인 의미라고 느껴지는데 어떻게 생각하시나용

2024-09-18 14:13 UTC, wuzoo commented on src/common/hook/useOutsideClick.ts
>  export const useOutsideClick = (handleToggle: () => void) => {
인자로 넘겨지는 콜백함수 네이밍에 `handle`은 좀 어색한 것 같아요 ! 차라리 명시적으로 `callback`으로 나타내는 방법도 좋은 것 같습니다.

2024-09-18 16:21 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
> +  };
저는 이게 좋습니다! view(jsx)에는 변수만 들어가야 한다는 주의라서..

2024-09-18 16:21 UTC, ptyoiy commented on src/shared/component/Header/Notification.tsx
>  const Notification = () => {
그게 좋겠네요!

2024-09-18 16:21 UTC, ptyoiy commented on src/shared/component/Header/Notification.tsx
> +            key={index}
API 연결때 처리하려고 했었는데, `// TODO: 어쩌구 저쩌구`를 잊어버려서 헷갈리게 만들었네요. 죄송합니당

2024-09-18 16:21 UTC, ptyoiy commented on src/shared/component/Header/Notification.css.ts
> +export const ulStyle = style({
아.. 당신도 정확하게 파악하지 못했군요. 저도 파악하지 못하겠어서 처리하지 못한 채 심신 미약 상태로 pr 먼저 던져본 것이었답니다. 안정을 되찾고 다시 찾아 봐야겠어요.

2024-09-18 16:21 UTC, ptyoiy commented on src/common/util/dom.ts
> + */
`@example` 예시 코드입니다. 다른 hook이나 util에도 어느 상황에서 어떻게 쓰면 좋을 지를 알려주는 목적에서 쓰는 것이니 다음엔 필요한 것으로 인식해주세요. 
참고로 이 util함수는 코드리뷰 리팩토링 후에 삭제 가능성이 있는 부분입니다.

2024-09-18 16:21 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
저도 맞다고 생각합니다

2024-09-18 16:22 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
> +  handleClick: () => void;
최소 단위의 컴포넌트(버튼, 인풋 등)가 아니라 이것저것 합쳐진 컴포넌트이다 보니 상속은 아닌 것 같습니다.
알림에서만 쓰는 컴포넌트기도 하고 전체를 감싸고 있는 div의 onClick만 정해주면 돼서요.

2024-09-18 16:23 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.css.ts
> +  listStyle: "none",
글로벌 스타일에는 없지만 어디선가 쓸까봐 추가하지 않았는데, figma 확인해보니 쓰는 곳이 없네요. 글로벌 스타일에 추가해 놓겠습니다.

2024-09-18 16:23 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
> +        onMouseOut={handleMouseOut}
figma 내용 상으로는 delete 버튼이 알림 메세지에 mouseover, focus되면 나타나는 방식이라 선택자로는 구현할 수 없겠더라구요, 그래서 `isActive` state를 사용해서 구현한 것입니다. 
더블 버튼은 저도 알고 있었던 내용인데, 간격 조정으로 css한테 크게 데여서 편한 길을 찾다 보니 저도 모르는 새에 넣어버렸더군요.. 잘 고쳐보겠습니다.

2024-09-18 16:23 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
> +  handleClick: () => void;
좋습니다!

2024-09-18 16:23 UTC, ptyoiy commented on src/shared/component/Header/Notification.tsx
> +      <ul className={ulStyle} role="list" aria-label="알림 목록" tabIndex={undefined}>
둘 다 css 간격 땜에 이것저것 테스트하다가 잊고 못 지웠던 거네요 감사합니다.

2024-09-18 16:23 UTC, ptyoiy commented on src/common/hook/useOutsideClick.ts
>  export const useOutsideClick = (handleToggle: () => void) => {
callback이 의미 상으로 더 좋아 보이네요!

2024-09-19 07:33 UTC, j-nary commented on src/common/component/AlarmListItem/index.tsx
> +  };
존중함둥 !

2024-09-19 10:23 UTC, ptyoiy commented on src/shared/component/Header/Notification.css.ts
> +export const ulStyle = style({
figma랑 figma에 써진 css대로 브라우저에 나타낸 것 간에 글자 간격이 다르게 나타나더라구요! 이걸 모른 채로 왜 다 안 들어가지?? 하며 삽질해댔네요.. 

theme.font를 수정하는 것은 이상한 것 같아서 일단은 브라우저에 나타나는 크기에 맞춰 알림 창을 약간 키우는 방향으로 해결했습니다.

2024-09-19 10:24 UTC, ptyoiy commented on src/common/component/AlarmListItem/index.tsx
> +          className={deleteButtonStyle({ active: isActive })}
아래 추천대로 버튼을 쳐냈습니다.

2024-09-19 10:38 UTC, j-nary approved these changes
LGTM 고생하셨습니다! 🚀

2024-09-19 11:13 UTC, ptyoiy commented
1. JSDoc 주석 추가
2. 변수명, 파일명, 디렉토리 적절하게 수정
3. figma와 동일한 간격으로 css 조정 (같은 css 구성인데도 글자 간격이 안 맞아서 알림 창이 약간 커짐)
4. css간격 조정하다 잘못 작성한 jsx구조 및 접근성 속성들 정상화
5. `use client` 지시어를 interaction이 있는 시작 점 컴포넌트로 이동 (UserMenu)
6. `mouseover`, `mouseout` 사용 시 접근성을 위해 `focus`, `blur`도 부착해야 하는 이슈를 위해 `useA11yhandler` 훅 작성
(`src/shared/hook`) (알림 창의 hover시 나타나는 delete 버튼 때문에 구현함)

2024-09-21 17:06 UTC, hwangjokim approved these changes
고생하셨습니다~

2024-09-21 17:06 UTC, hwangjokim commented on src/shared/component/Header/Alarm.css.ts
> +      boxShadow: "none",
이 스크롤바 속성들 그냥 헤더 말고, 프로젝트 전역에 적용해도 되지 않을까 싶은 생각이 있습니다

2024-09-22 04:47 UTC, ptyoiy commented on src/shared/component/Header/Alarm.css.ts
> +      boxShadow: "none",
height 속성을 정의한 부분인 양 끝 버튼 크기를 제외하면 그렇게 하는 것이 좋겠네요. 의견 감사합니다!

2024-09-22 05:07 UTC, ptyoiy commented on src/shared/component/Header/Alarm.css.ts
> +      boxShadow: "none",
전역에 정의하려고 보니 globalStyle에는 selectors나 의사 선택자를 쓸 수 없다고 하네요.. 그래서 아쉬운대로 theme 파일에 추가하였습니다.

2024-09-22 08:46 UTC, merged