[ Feat ] Context를 통한 TabGroup 컴파운드 컴포넌트 구현
GAMZA-BAT/algohub-client pull request #46
Opened 2024-09-20 11:48 UTC by wuzoo

## #️⃣ Related Issue
Closes #43 

## ✅ Done Task
  - [ ] Tab 컴포넌트 구현

## ☀️ New-insight

기존에 `Tab` 컴포넌트를 구현할 때는 `TabPanel`을 따로 구현하지 않고, 단지 `selected`된 탭 `id` 만을 고려하여 해당 컴포넌트를 사용하는 쪽에서 이에 따른 분기처리를 하도록 구현하였습니다.

하지만 `Children` API를 통해서 순서로대로 JSX에 구조화 되어있는 `Panel`을 `id`에 따라 탭 컴포넌트에서 제어하는 방식으로도 구현할 수 있다는 것을 알고 해당 방식으로 구현하였습니다.

## 💎 PR Point

### Tab Variant 구분

- 탭 1
<img width="735" alt="image" src="https://github.com/user-attachments/assets/382a2cc3-1ef7-4dda-b678-173f5df9e3f1">

- 탭2
<img width="219" alt="image" src="https://github.com/user-attachments/assets/907013a8-7cca-4480-90cd-d54c26c1c379">

저희 어플리케이션에서 탭이 2가지로 구분되는 것을 확인하였는데요. 따로 네이밍을 지정해주려고 했지만, 적당한 이름을 생각하지 못했고 중요도로 구분할 수 있다고 생각하여 `primary`, `secondary`로 명명하였습니다.

두 개의 탭은 사실 그렇게 UI적으로 큰 차이를 보이지는 않는데, `Indicator` 색깔과 안에 `Tab` 컴포넌트의 크기 정도가 달라지는 것을 확인할 수 있었고, 이에 따라 `variant`로 구분해주었습니다.

### Context 도입
저는 사실 `App` 수준에서 `Context`를 사용하는 것을 선호하지는 않는데, 탭 컴포넌트나 아코디언, 드롭다운 등의 복잡한 구조에서의 컨텍스트 도입에는 꽤나 긍정적으로 생각하고 있습니다. 국소적으로 상태를 공유하기 때문에 렌더링 측면에서도 큰 영향을 끼치지 않습니다.

현재 `Context`로 두 가지 상태를 선언하였는데 `variant`와 `selectedTab` 입니다. 사실 `variant`는 상태를 업데이트할 일이 거의 없을 것 같다고 생각은 합니다..

그리고 좀 더 애플리케이션이 디벨롭된다면 `탭`을 추가하거나 삭제하는 동작도 충분히 구현할 상황이 생길 수도 있다고 생각하여, `useState`를 사용하는 것이 아니라 좀 더 비즈니스 로직적으로 구분을 확실하게 하기 위해서 `reducer`로 구현하였습니다. 로직에 대한 가독성이 생길 뿐더러, 상태를 업데이트하는 과정에서도 도메인이 확실하게 나타난다는 장점이 있는 것 같습니다.

### TabGroup 컴포넌트를 통한 합성

탭 컴포넌트를 사용하실 때는 `TabGroup` 컴포넌트를 `import` 하여 컴포넌트 합성하여 사용할 수 있도록 구현하였습니다. 합성 컴포넌트 구현 과정에서 `context`를 사용하여 불필요한 `prop`들을 줄일 수 있었습니다.

## 📸 Screenshot

https://github.com/user-attachments/assets/82d38c2f-1a87-4086-b874-4b418605cf1e

2024-09-20 13:38 UTC, ptyoiy commented
고생 많으셨습니다! 일단 전체 코드 리뷰는 양이 많아서 21일에 찬찬히 읽어보도록 하겠습니다..

이슈 관련해서는 톡방에서 얘기한 대로 currentColor를 이용하면 될 것 같아요. 
생각해보다가 좋은 방법이 떠올랐는데, `svgr.config.js`에서 svg파일의 모든 `fill`, `stroke` 속성을 currentColor로 바꾸는 기능이 있습니다. 이걸 사용하면 `<IcnAlarm fill={"red"}>` 처럼 사용했을 때 바로 색상이 바뀔 거에요. 

그리고 2개 이상 색상이 들어있는 아이콘들에 대해서는 `['path:nth-child(n)' as string]`나 `['path' as string]` 같이 선택자를 사용해서 바꾸는 편이 좋을 것 같아요. 배경 색이나 테두리까지 있는 아이콘보다 `tab`에 사용되는 아이콘들처럼 없는 아이콘이 더 많거든요.

스타일 적용은 fill인지 stroke인지 미리 작성해 놓고 쓸 수 있게 동적 style을 만들어 두거나, 그때그때 svg 파일 구조를 보고 stroke인지 fill인지 확인해서 `css.ts` 파일에 style을 만드는 방법을 생각할 수 있겠네요.

- 첫 번째 방법의 경우 첫 아이콘 사용 시 마다 이런 느낌으로 작성해서 어디 폴더에 모아두고 쓰면 좋을 것 같고
```typescript
// style 정의
const dynamicIcnXyzStyle = (value: string) =>
  style({
    fill: value,
  });
// 사용
const dynamicClass = dynamicIcnXyzStyle('red');
<IcnXyz className={dynamicClass } />
```

- 두 번째 방법의 경우는 중복 작업이 될 수 있어서 1번이나 다른 방법을 쓰는 게 나을 것 같네요.

2024-09-21 13:22 UTC, ptyoiy commented on src/common/component/Tab/Tab.tsx
> +      // biome-ignore lint/a11y/noNoninteractiveElementToInteractiveRole:
biome lint 경고가 왜 떴는지 확인하기 위해 정보를 좀 찾아봤습니다.
보통 UI 컴포넌트 라이브러리들이나 여러 공식 문서에서 `div`와 `button`으로 tablist와 tab을 구현하더라구요.
그렇다고 `ul`, `li`를 사용해서 tab을 구성하면 안되거나, 안 좋거나 하지는 않고 `non-interactive` 태그다 보니 지금처럼 role, tabindex, event들을 부착 시키면 기능 상으로는 차이가 없다고 하네요.

경고 관련해서는 MDN의 Tab 관련 내용 중 `Best Practice`를 소개하는 내용에서 추측을 해봤는데, 위 내용대로 role, tabindex, event 등을 부착해야 하니까 다 부착돼있는 `button`으로 하라고 추천하더라구요. 그렇다고 저 lint 경고를 전역적으로 끄는 것 보다는 지금처럼 개발하는 사람이 원하는 방식으로 잘 구현하고 경고를 직접 끄는 편이 좋을 것 같습니다.

2024-09-21 13:22 UTC, ptyoiy commented on src/common/component/Tab/Tab.tsx
> +    >
[공식 가이드](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/)를 보면 `aria-selected`, `aria-controls`, `aria-labelledby`를 추가해야 되겠어요. 각각은 `탭 활성화 여부`, `탭과 연결된 tab panel`, `관련된 부모 요소 id`를 의미한다고 해요. 이걸 위해 `tab panel`에도 id 등 여러 속성을 추가해야 되겠네요!

그리고 tab간 전환은 tab키가 아니라 방향키 및 엔터/스페이스바로 해야된대서 활성화 여부에 따라 나머지 탭의 tabindex를 -1로 해야할 것 같아요.

2024-09-21 13:23 UTC, ptyoiy commented on src/common/component/Tab/TabProvider.tsx
> +    case "SetVariant": {
얘는 안 쓰지 않을까요? 없애버려도 괜찮을 듯 하네요.

2024-09-22 06:33 UTC, wuzoo commented on src/common/component/Tab/Tab.tsx
> +      // biome-ignore lint/a11y/noNoninteractiveElementToInteractiveRole:
좋은 말씀 감사합니다.

사실 제가 생각하는 `button`이라는 정말 시맨틱한 태그를 쓰는 경우는, 말 그대로 어플리케이션의 핵심적인 역할을 하는 말 그대로 버튼, 혹은 유사 기능을 하는 다른 요소들에게 붙혀주는 것 같아요.

이런 탭과 같은 경우에는 규한님 말씀대로 다른 태그들을 쓰되, 버튼이라는 역할만을 알려주는 것을 선호하는 것 같습니다.

규한님 말씀처럼, 개발에 있어서 큰 규칙을 어기지 않는 이상 선호도에 따라 개발하고 때에 따라서 린트 꺼주는 것도 좋은 방법인 것 같습니다 !

2024-09-22 06:33 UTC, wuzoo commented on src/common/component/Tab/Tab.tsx
> +    >
오호 .. `wai-aria`를 잘 사용한다고 생각했는데, 요런 것들을 보면 아직은 미숙한 것 같네요 !

좋은 정보 감사합니다 ~ 반영하겠습니다 !

2024-09-22 06:33 UTC, wuzoo commented on src/common/component/Tab/TabProvider.tsx
> +    case "SetVariant": {
인정합니다.. 지우겠습니다 !

2024-09-22 06:33 UTC, wuzoo commented on src/common/component/Tab/TabProvider.tsx
> +    case "SetVariant": {
인정합니다 .. !

2024-09-22 06:58 UTC, hwangjokim reviewed
고생하셨습니다~~~

2024-09-22 06:58 UTC, hwangjokim commented on .storybook/main.ts
여담이긴  한데, 현재 포매터같은 경우가 CI에서 워닝으로만 나와서 계속 포매팅 diff가 잡히는게 조금 아쉽네요 
그래서 이것 Error로 변경하고, 현재 포매팅 안된 파일들 일괄 적용하는 PR 올리는 것 회의 안건에 추가해보겠습니다

2024-09-22 06:58 UTC, hwangjokim commented on src/common/component/Tab/index.css.ts
> +        padding: "26px 17px",
rem 말고 px 단위 쓰신 이유가 있으실까요? 이 css파일에서 모두 px 단위를 쓰고있네용

2024-09-22 06:58 UTC, hwangjokim commented on src/common/component/Tab/TabProvider.tsx
> +  if (context === undefined || context === null) {
context가 null 말고 undefined인 상황은 없는 것 아닌가용?

2024-09-22 06:58 UTC, hwangjokim commented on src/common/component/Tab/TabProvider.tsx
> +  return context?.dispatch;
바로 위에 방어로직 있으니, ? 없이 `context.dispatch`로 return해도 될 것 같아요

2024-09-22 06:58 UTC, hwangjokim commented on src/common/component/Tab/TabProvider.tsx
> +  selectedTabId: string | number;
tabId 현재는 모두 idx(number)로만 쓰고 계신 것 같은데, string 타입은 어떤 경우를 고려하기 위해 갖게  되었나요?

2024-09-22 07:43 UTC, wuzoo commented on src/common/component/Tab/TabProvider.tsx
> +  selectedTabId: string | number;
사용자 입장에서 `tabId={1}` 혹은 `tabId='1'` 둘 다 prop으로 설정했을 때 모두 동작하도록 설정하였습니다 !

2024-09-22 07:43 UTC, wuzoo commented on src/common/component/Tab/TabProvider.tsx
> +  return context?.dispatch;
헛 맞습니다 ! 수정하겠습니다

2024-09-22 07:43 UTC, wuzoo commented on src/common/component/Tab/TabProvider.tsx
> +  if (context === undefined || context === null) {
`context`가 `undefined`되는 경우는 다양합니다 !

1. Provider를 설정하지 않았을 경우
2. Provider 구독 컴포넌트 하위에서 사용하지 않았을 경우
3. Provider로 전달한 `value`가 `undefined`일 경우 

입니다. !

2024-09-22 07:43 UTC, wuzoo commented on .storybook/main.ts
맞아요 ㅠ 좋습니다 !

2024-09-22 07:43 UTC, wuzoo commented on src/common/component/Tab/index.css.ts
> +        padding: "26px 17px",
이거 반영하겠습니다. 제가 처음에 작업할 때 `fontSize: 62.5%`를 해서 다른 px 값도 1rem -> 10px 되는 줄 잠시 착각하고 있었어요.

근데 다른 패딩이나 마진에서 사용할 때는 일일히 변환해주어야 하는게 좀 귀찮아서 일단은 px로 하긴 했는데 .. 수정하겠습니다

2024-09-22 07:44 UTC, hwangjokim commented on src/common/component/Tab/TabProvider.tsx
> +  if (context === undefined || context === null) {
아 Provider 하위 아닌경우 생각 못했네요 감사합니다 :D

2024-09-22 07:59 UTC, j-nary requested changes
LGTM! 보고 많이 배워갑니다! 좋은 코드 감사해용
자잘한 코리 몇 개랑 인터랙션만 확인해주세요 :)

2024-09-22 07:59 UTC, j-nary commented on .storybook/preview.ts
> +import "../src/styles/globalStyles.css";
"@/.." 전역 path로 통일해용 ~!

2024-09-22 07:59 UTC, j-nary commented on src/common/component/Tab/TabPanels.tsx
> +    </div>
이렇게 하신 의도가 따로 있으신걸까요?

`idx+1 === +selectedTabId` 로 축약할 수 있을 것 같고!
무엇보다 ``Children.toArray(children)[+selectedTabId - 1]}` 로 조건부 렌더링 하면 되는 코드 아닌가 싶습니다!

2024-09-22 07:59 UTC, j-nary commented on src/common/component/Tab/TabProvider.tsx
> +  if (context === undefined || context === null) {
둘다 falsy한 값이니 `if (!context)` 로 줄일 수 있을 것 같네요!

2024-09-22 07:59 UTC, j-nary commented on src/common/component/Tab/index.css.ts
인터랙션 추가해주세요!

https://github.com/user-attachments/assets/223537c5-7253-44e2-98a3-6e36fb8172e7

2024-09-22 09:15 UTC, ptyoiy commented on src/common/component/Tab/Tab.tsx
> +    >
`tab`의 `aria-controls`에 해당하는 `id` 속성을 해당 `tab panel`에 붙여주시고, 반대로 `tab panel`의 `aria-labelledby`에 해당하는 `id` 속성을 `tab`에 붙여주시면 완성이네요. 고생 많으셨습니다!

2024-09-25 14:33 UTC, wuzoo commented on src/common/component/Tab/TabPanels.tsx
> +    </div>
하나의 패널로 렌더링되는 부분을 `section` 요소로 수정하여서 `map` 부분은 유지했고,  `idx + 1 === +tabId`로 수정해두었습니다 !

2024-09-25 14:33 UTC, wuzoo commented on src/common/component/Tab/index.css.ts
이거 밑에 인디케이터 바만 인터랙션 주면 되는거 아닌가요 ? 백그라운드도 저렇게 반영되야 하나요 ?

2024-09-27 12:34 UTC, ptyoiy approved these changes
aria 속성 코멘트 쪽에 추가로 언급한 id 속성 추가 해주세요!

2024-10-02 12:29 UTC, j-nary approved these changes

2024-10-02 14:02 UTC, merged