[ Feat ] onboarding page 구현 및 스토리북 테스트
GAMZA-BAT/algohub-client pull request #48
Opened 2024-09-21 00:11 UTC by ptyoiy

## #️⃣ Related Issue
Closes #42 

## ✅ Done Task
  - [ ] onboarding page 구현
  - [ ] section간 스크롤 이동 기능 적용(scroll-snap)
  - [ ] 스토리북 테스트

## ☀️ New-insight

- section 구현
  - `h 시리즈 태그`
    - `h1`, `h2` 같은 태그는 한 페이지에서 쓸데없이 반복 사용되어선 안된다고 합니다.
    - 온보딩 페이지는 `intro` section과 `feature-1`, `feature-2` section으로 나뉘는데, `feature`의 경우 내용이 이어지므로 `h2`를 중복 사용했습니다.
  - `Text`
    - 보라색으로 강조하는 글자들의 경우 `<strong>`과 `<em>` 사이에서 고민했는데, `strong`은 `중요성` `긴급성` `심각성`을 알리는 `강한 강조`이고 em은 문장 내 특정 문맥을 강조하는 `덜 강한 강조`라 해서 `em`을 사용하였습니다.
    - 작은 글자의 경우 `<small>`을 사용했습니다.
  - `next/Image`
    - 자동으로 최적화를 진행하며 이미지 품질을 낮추는데, 이를 방지하려면 `unoptimized` 속성을 부여하면 됩니다.
    - `priority` 속성은 제일 먼저 이미지를 가져오게 하는 속성인데, 첫 화면에 보이는 이미지에 적용하면 됩니다.
  - Vanilla Extract의 `recipe`와 `styleVariants` 차이
    - `recipe`는 기본 `base`를 놓고 여러 variant를 선택하는 상황에 사용하고, `styleVariants`는 기본 base 없이 단순한 조건별 스타일을 선택할 때 사용합니다. 두 함수의 기능을 생각했을 때 제가 사용한 대부분의 recipe들을 `styleVariants`로 변경할 수 있겠으나, base 코드가 긴 것이 많아서 변경했을 때 이점이 딱히 없다고 생각합니다.
     
- section간 스크롤 이동
  - 구현 방법 선택
    - `라이브러리`, `js로 직접 구현(scrollIntoView(), window.scroll())`, `css scroll-snap` 3개의 선택지가 있습니다.
    - 스크롤하며 다양한 부가 애니메이션이 필요하지 않고, 단순히 부드러운 section 간 이동 스크롤만 구현하면 되기 때문에 css의 scroll snap을 사용했습니다. 
    - 처음에 적용이 안돼서 뭐가 문제인지 오래 해맸는데, 결론적으로 스크롤을 표시할 부모 요소에는 `overflow`, `scrollSnapType`, `height:100%` 3개의 속성을 필수로 부여하고, 자식 요소들에는 `scrollSnapAlign` 속성 하나만 부여하면 작동합니다.

- route segment stroy 적용
  - `Layout.tsx`가 적용되지 않기 때문에 직접 적용시켜야 합니다.
  - RootLayout과 해당 page.tsx가 사용하는 모든 Layout을 decorators 속성에서 사용해주면 됩니다.
  - page 스토리를 보면 컴포넌트 스토리가 안 보이는 버그가 있는데 좌상단 storybook 로고 클릭해서 새로고침? 해주면 다시 보입니다.
      ```typescript
      const meta: Meta<typeof OnboardingPage> = {
        title: "page/onboarding",
        component: OnboardingPage,
        parameters: {
          design: {
            type: "figma",
            url: "",
          },
        },
        decorators: [
          (Story) => (
            <RootLayout> // 최상위 Layout (html, body)
              <Layout> // page가 사용하는 Layout
                <Story /> // page.tsx
              </Layout>
            </RootLayout>
          ),
        ],
      };
      ```

## 💎 PR Point

- 컴포넌트 트리 구조
  ```bash
  Onboarding route
    ├── <Header> (RootLayout)
    ├── <main> (page.tsx)
    │   ├── <Section1>
    │   ├── <Section2>
    │   └── <Section3>
    └── <Footer> (onboarding Layout)
  ```
- `section` 별 간격 조정 로직
  - `Section 1` (`메인 컨텐츠` + `하단 Arrow 애니메이션 버튼`)
    - `메인 컨텐츠`와 `Arrow`는 `height:100vh`, `dispaly: flex`를 사용해 한 화면 내에 2개 층으로 구성
    - 모든 `Text`들은 전체 Section에서 동일한 left padding을 갖기 때문에, 내부 요소들의 개수에 따라 위치가 달라지는 `dispaly: flex`보다는 `width: 120rem`을 나눠 쓰는 `2x1 중앙 정렬 grid`를 구성해서 고정된 위치를 갖게 함
  - `Section 2`
    - 1과 동일한 `120rem width`의 grid 사용
    - 대신 이미지가 대각선 방향으로 이동해야 하므로 이미지 위치를 위해 column을 잘 조정한 2x2 grid로 변경 (recipe)
    - 이미지는 `gridColumn: 2`, `gridRow: 2` 를 통해 `grid`의 4번째 칸에 위치하게 함
  - `Section 3`
    - 1과 동일한 `120rem width`의 grid 사용
    - 이번엔 이미지가 중앙 정렬되어야 하므로 `2x2 grid`로 구성하되 아래 층을 하나로 통합한 후 `flex`와 `justify-content: center`로  중앙 정렬
    - 아래 층 두 칸을 하나로 통합은 `gridColumn: 1 / span 2` 로 가능
- Text 타입 별로 나누기
  - `introTextStyle`을 `recipe`로 만들어서 type별로 다른 스타일을 갖게 한 뒤 여러 변형을 static 메서드로 정의
    ```typescript
      const Text = ({ children }: PropsWithChildren) => {
        return <p className={introTextStyle()}>{children}</p>;
      };
      
      Text.Em = ({ children }: PropsWithChildren) => {
        return <em className={introTextStyle({ type: "em" })}>{children}</em>;
      };
      
      Text.Alphabet = ({ children }: PropsWithChildren) => {
        return (
          <span className={introTextStyle({ type: "alphabet" })}>{children}</span>
        );
      };
      
      Text.Small = ({ children }: PropsWithChildren) => {
        return <small className={introTextStyle({ type: "small" })}>{children}</small>;
      };
    ```
## 📸 Screenshot

![Animation2](https://github.com/user-attachments/assets/2ab5cda0-4d1d-4515-83b6-4a6c628ae23f)

2024-09-22 07:24 UTC, wuzoo reviewed
깔꼼하네요 고생하셨습니다 ! 🚀🚀🚀

리뷰에 남긴 의견 정도만 확인해주시면 감사하겠습니다 !

2024-09-22 07:24 UTC, wuzoo commented on src/view/onboarding/component/Section/Section2.tsx
> +            </Text>
요 타이포그래피 공통 컴포넌트로 빼도 좋을 것 같아요 !

`variant`를 받아 특정 베리언트값에 따라 디자인 시스템의 특정 `font` 객체를 적용한 텍스트를 반환해주도록 구현한다면, 좋은 타이포 컴포넌트가 될 것 같습니다.

2024-09-22 07:24 UTC, wuzoo commented on src/view/onboarding/component/Section/Section2.tsx
> +            </Text>
그리고 지금 랜딩페이지들에 있는 이미지를 UX 개선을 한다면 `intersection observer` 적용해도 좋을 것 같아요.

마침 스크롤 `snap`도 적용되어있으니 해당 뷰에 진입할 때마다 이미지에 fade in 효과와 같은 애니메이션 적용해준다면 더욱 좋을 것 같습니다.

인터섹션 옵저버를 설정한다면 아마도 `ref`를 연결해줄 필요가 있을 것 같은데, 그럼 `id`를 하나씩 설정해줄 필요 없이 `ref`를 통해서 `scrollIntoView`도 가능할 것 같습니다.

2024-09-22 07:24 UTC, wuzoo commented on src/styles/globalStyles.css.ts
> +
요고는 왜 글로벌 스타일로 지정해두신건지 궁금합니다 !

2024-09-22 07:24 UTC, wuzoo commented on src/app/onboarding/page.tsx
> +
저는 개인적으로 전체 뷰를 이미 `view/component`에서 만들어서 `page.tsx`에서 하나만을 렌더링하는 것보다는, 핵심적인 컴포넌트들(아토믹 디자인 시스템을 기준으로 한다면 오가니즘 정도를 `view`에서 만들고 페이지를 `page.tsx`에서)을 만들어놓은 후 `app/page`에서 조립하는 방향이 더 좋을 것 같아요 !

사실 큰 상관은 없지만, `page.tsx` 파일 자체가 단 하나의 컴포넌트를 렌더링하기 위해서 존재한다는게 제 입장에서는 조금은 어색한 것 같습니다.

다른 분들 의견 궁금하네요 !

2024-09-22 09:38 UTC, ptyoiy commented on src/styles/globalStyles.css.ts
> +
이건 몇 가지 구현 선택지 사이에서 고르다가 미처 처리하지 못한 똥입니다.. 제가 선택지를 골라 놓고 후처리를 덜했네용.

처음에는 아래 의견처럼 `page.tsx`에 `Sections` 컴포넌트의 내용물을 넣으려고 했었습니다. 그런데 그러려고 보니 `section`들을 감싸고 있는 `main` 태그에 들어갈 `style`을 컨벤션 때문에 저 멀리 view 폴더에서 import 해야 되겠더군요..
뭔가 맘에 안 드는데? 해서 어차피 다른 곳에 스크롤 기능도 없는데 html에 전역으로 붙일까, `Sections` 컴포넌트를 따로 만들고 style을 붙인 main태그를 사용할까 고민했었답니다. 근데 어째 둘 다 선택했었네요 ㅋㅋ!

2024-09-22 09:39 UTC, ptyoiy commented on src/styles/globalStyles.css.ts
> +
저도 아래 의견처럼 page에서 조립하는 걸 선호하기 때문에 그 방식으로 수정하겠습니다!

2024-09-22 09:43 UTC, ptyoiy commented on src/view/onboarding/component/Section/Section2.tsx
> +            </Text>
이미지 효과가 디자인 시안에는 적혀있지 않아서 냅둔거긴 한데, 저도 그렇게 하는 게 좋다고 생각해요. 다른 분도 동의하시면 적용하겠습니다!

2024-09-22 09:49 UTC, ptyoiy commented on src/view/onboarding/component/Section/Section2.tsx
> +            </Text>
타이포그래피의 경우 구조만 차용해서 공통 컴포넌트로 따로 만들어야겠어요. 온보딩 페이지의 경우 디자인 시스템의 `theme.font`를 사용하지 않으면서 반복 사용되길래 따로 만든 것이거든요.

2024-09-22 10:02 UTC, ptyoiy commented on src/styles/globalStyles.css.ts
> +
main에 스크롤 스타일을 줬더니 `Footer`가 스크롤 바깥 영역에 있어서 보기 흉해지는 버그가 있네요. 
scroll-snap이 `footer`까지 적용돼야 해서 스크롤 스타일을 입힌 div로 `Main`과 `Footer`를 묶는 방식으로 해결했습니다.

2024-09-23 17:54 UTC, j-nary requested changes
고생하셨습니당 !! 코리 확인 부탁드려용 :)

2024-09-23 17:54 UTC, j-nary commented on src/view/onboarding/component/Section/index.tsx
> +    </div>
이정도는 page.tsx에 위치시켜도 되지 않을까요? 컴포넌트로 분리해준 이유가 궁금합니다!

2024-09-23 17:54 UTC, j-nary commented on src/view/onboarding/component/.gitkeep
불필요한 `.gitkeep` 은 삭제해주세요!

2024-09-23 17:54 UTC, j-nary commented on src/view/onboarding/component/Footer/index.tsx
> +const Footer = () => {
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/46a35f80-73c4-41ad-9189-cb518267cc7f">

실행시켜보니 Footer랑 겹치네오!

2024-09-23 17:54 UTC, j-nary commented on src/app/onboarding/page.tsx
onboardingPage path는 root 입니당 파일 이동 부탁드려요 :)

2024-09-23 17:54 UTC, j-nary commented on src/view/onboarding/component/Section/Section1.tsx
> +            </div>
Link 이동까지 기능 넣어주세용!

2024-09-23 17:54 UTC, j-nary commented on src/view/onboarding/component/Section/Section2.tsx
> +            </Text>
좋은 의견인 것 같아용 ~!

2024-09-24 20:01 UTC, ptyoiy commented on src/view/onboarding/component/Footer/index.tsx
> +const Footer = () => {
화면 크기에 따라 section이 필요로 하는 길이보다 짧아서 그런건데, 잘 수정해보겠습니다.

2024-09-24 20:01 UTC, ptyoiy commented on src/view/onboarding/component/Section/Section1.tsx
> +            </div>
아무 생각 없이 다음 작업인 로그인/회원가입 구현에서 처리하려고 했네요. 수정하겠습니다!

2024-09-24 20:04 UTC, ptyoiy commented on src/view/onboarding/component/Section/index.tsx
> +    </div>
아름답기 때문입니다.

2024-10-02 14:31 UTC, j-nary approved these changes
LGTM 고생하셨습니다! conflict만 잡고 머지해주세요!

2024-10-03 09:53 UTC, wuzoo approved these changes
고생하셨습니답 !

2024-10-03 09:53 UTC, wuzoo commented on src/view/onboarding/hook/useFadeIn.ts
`useIntersectionObserver` 라는 커스텀 훅으로 생성하고, 콜백을 넘겨서 인터섹션 시에 실행시키도록 구현하는게 더 사용성 입장에서 좋을 것 같습니다 !!

2024-10-03 11:31 UTC, hwangjokim commented
이거 CI Fail인데, 해결하고 머지해주셔도 될것같습니다

2024-10-03 18:11 UTC, merged