Feat/#54/form
GAMZA-BAT/algohub-client pull request #57
Opened 2024-09-25 16:24 UTC by ptyoiy

## #️⃣ Related Issue
Closes #54 

## ✅ Done Task
  - [ ] Form 컴포넌트 패밀리 구현
  - [ ] 접근성 속성 확인
  - [ ] 다양한 사용법을 스토리로 작성 (일관된 사용 패턴)

## ☀️ New-insight

- Form 구조
외국 개발자 커뮤니티에서 잘 짜여진 구조로 소문난 생성형(코드 제공형) ui 컴포넌트 라이브러리인 `shadcn`의 form 구조를 가져왔습니다. [Link](https://ui.shadcn.com/docs/components/form)
현업에서 자주 사용되는 `react-hook-form`과 `zod`를 사용한 점이 마음에 들어서 이것을 채택했습니다.
다만 tailwind css를 기반으로 만들어져 있기에 이 부분은 `Vanilla Extract`와 `util/string.ts`에 추가한 `joinClassName()`으로 처리했습니다.

  - Slot 패턴 (asChild 패턴)
  Form 컴포넌트 패밀리 중 form field 요소(input 등)를 `children`으로 받는 컴포넌트인 `<FormControl>`은 `<Slot>`으로 구현되어 있습니다. `<Slot>`은 `radix-ui`라는 라이브러리에서 가져온 것(1.05KB)인데 역할은 `<>{children}</>`과 동일하나 `props`를 children에 부여할 수 있습니다. 그에 따라 별다른 코드(React.cloneElement 등)없이 부여해야 할 `id`와 `aria` 속성을 form field 요소에 주입할 수 있게 되죠. 
제가 #52 에서 구현했던 `Menu` 컴포넌트의 `TriggerButton`에는 버튼에 부여할 props를 object로 만들고 jsx에서 부여하는 방식으로 만들었는데, `renderTriggerButton`을 함수형으로 만들거나 `cloneElement`를 사용하여 구현할 수 있습니다. 이걸 `<Slot>`을 사용한다면 좀 더 코드가 간결해지고 공통 컴포넌트에 적합한 구조가 될 것이라 생각합니다. 이런 패턴들에 관한 내용은 이 [블로그](https://velog.io/@ctdlog/radix-ui-aschild-pattern)를 참고해보세요!

- react-hook-form
스토리의 여러 variants를 확인해보면 느껴지겠지만 사용법이 패턴화가 가능할 정도로 간단합니다. uncontrolled 방식(state가 아닌 ref로 값 관리)으로 form field를 제어하기에 form 관리에서 주요 논쟁 거리인 리렌더링 이슈도 해결했습니다. 특히 유효성 검사 및 결과 처리가 독립적으로 이뤄지기 때문에 `zod`같은 라이브러리를 통합하기도 편리하고 결과 값을 view에 적용하기도 좋은 것 같습니다.

## 💎 PR Point

- **Form 컴포넌트가 제공하는 기능**
1. 패턴화된 form 작성 방식으로 개발 및 코드 리뷰 속도가 빨라짐
2. `aria`, `id`속성 자동 부여, 혹은 `useFormField()`훅으로 수동 부여 가능 (context라서 `<FormItem>`의 `children`만 사용 가능)
3. zod의 schema를 통한 유효성 검사 로직 분리 작성 가능
4. 유효성 검사 결과를 react-hook-form의 `useForm()`훅의 `return`값에서 꺼내 사용 가능

- **Form 컴포넌트 사용 방법** (스토리에서 다양한 사용법을 확인해 주세요! 사용 방법은 아래 코드의 주석과 동일합니다.)
  - data container (return문 윗부분)
  1. zod로 `schema` 작성
  5. react-hook-form의 `useForm()` 훅의 인자로 form에 적용할 `schema`와 `기본값` 등록
  6. `onSubmit` 함수 작성  
  <br>

  - jsx (1~9번이 보일러 플레이트 코드 마냥 반복되며, 개발자는 zod로 만드는 `schema` 및 5, 6, 7번에 들어갈 요소에만 집중하면 됩니다!)
    - 코드의 맨 위 3줄 `<Form>~<div className={storyContentStyle}>`먼저 만들어 두고
    - 필요한 `<input>`별로 `<FormField>` `<FormItem>` `<FormControl>` `<input>`을 아래 순서와 **똑같이** 작성하시면 됩니다.
  ```typescript
  <Form {...form}> // 1. Form 태그에 const form = useForm({ ... }) 변수 삽입
    <form onSubmit={form.handleSubmit(onSubmit)} className={storyFormStyle}> // 2. html form 태그 사용
      <div className={storyContentStyle}> // 3. (선택) form field 요소들을 flex로 배치할 div 컨테이너

        <FormField // 4. FormField 하나당 한 form field 요소(<input>) 사용
          control={form.control}
          name="id" // 5. 이 form field의 이름(zod 사용 시 schema에 작성된 속성들만 사용 가능)
          render={({ field }) => (
            <FormItem>
              <FormLabel isError={idError}>아이디</FormLabel> // 6. (선택) 라벨이 필요하면 <FormControl>의 형제 요소로 사용
              <FormControl> // 7. 사용할 form field를 감싸는 컴포넌트
                <input {...field} placeholder="아이디" /> // 8. 표시할 form field 요소/컴포넌트에 field 매개변수 삽입
              </FormControl>
            </FormItem>
          )}
        />

        <FormField // 9. (선택) 추가 form field는 위와 동일
          control={form.control}
          name="password"
          render={({ field }) => (
            <FormItem>
              <FormLabel isError={passwordError}>비밀번호</FormLabel>
              <FormControl>
                <input {...field} placeholder="비밀번호" />
              </FormControl>
            </FormItem>
          )}
        />

      </div>
      <Button type="submit" size="medium"> // 9. form submit 역할을 할 버튼 컴포넌트
        로그인
      </Button>
    </form>
  </Form>
  ```
## 📸 Screenshot

![form](https://github.com/user-attachments/assets/67c20a29-a882-4bd8-8390-483858f4a185)

![form2](https://github.com/user-attachments/assets/a40e7aac-39a7-4915-881a-2d28341a484f)

2024-10-02 10:12 UTC, wuzoo approved these changes
역시 잘하시네요 ! 고생하셨습니다 ~ 🚀

2024-10-02 10:12 UTC, wuzoo commented on src/common/component/Input/index.tsx
> +        className={clsx(inputStyle({ size, isError }), className)}
근데 혹시 `clsx`를 사용하지 않고도

```ts
className={`${inputStyle} ${className}`}
```
으로 될텐데 아닌가요 ? 스타일들이 전부 문자열로 변환되어서 이렇게 사용하는걸로 알고 있어요 !

2024-10-02 10:12 UTC, wuzoo commented on src/shared/component/Form/index.tsx
`hook-form`의 `Controller`를 제대로 사용해본 적은 없는데 꽤나 복잡하네요 .. !

일단 PR 남기신 거 읽어보고 코드리뷰를 남기는 시점에도 제가 좀 정리하고 이해한게 맞는지 여쭤보기 위해 써볼게요

1. `FormField`는 일단 훅 폼의 `Controller` 모든 `props`를 넘기는 동시에, 상단에 Provider로 `name` 프로퍼티를 하위 컴포넌트에 제공해주기 위해 사용.
2. `FormItem`은 하나의 인풋을 이루는 `label`, `text`, `input` 과 같은 컴포넌트를 감싸는데, 하위 컴포넌트들에게 `id`를 제공해주기 위해 사용
3. `FormControl`은 `Input`을 렌더링하는데, 앞서 언급한 두 프로바이더에서 제공하는 값들로 접근성을 챙긴 하나의 인풋 컴포넌트를 `Slot`으로 렌더링
4. `Label`, `SupportingText`는 `prop` 건내주면서 그대로 렌더링

정도 ! 인 것 같네요 ?

근데 이 트리구조를 살펴보니 사실 `Item -> Control -> Slot -> Input` 으로 이어지는 이 렌더링 흐름이 사실 조금은 과하기도 한 것 같다는 생각을 했어요. 그래도 꽤나 유명한 ui 라이브러리에서 채택한 이유가 있지 않을까 싶기도 하네요

`Input`이 `label`과 `text`와 `id`, `name`의 모든 `prop`을 받을 수 있다면 이 좀 깊은 뎁스의 트리 구조가 간결해질 수도 있다는 생각이 들기도 하네요 ! 좋은 코드인 것은 알지만 같은 유연함과 확장성을 챙기면서 가독성 있게 단순화해볼 수도 있을 것 같습니다

2024-10-02 10:12 UTC, wuzoo commented on src/shared/component/Form/Form.stories.tsx
> +    });
`react hook form` + `zod` 저도 사용해보지는 않았지만 정말 효과적인 조합이라고 들었는데 좋네용 ~

2024-10-02 10:12 UTC, wuzoo commented on src/shared/util/form.ts
> +) => {
아래의 함수도 그렇고 여기서 `touched`, `dirty` 필드는 어떤 쓰임인지 궁금해요 !

2024-10-02 10:27 UTC, ptyoiy commented on src/common/component/Input/index.tsx
> +        className={clsx(inputStyle({ size, isError }), className)}
종종 `className`에 `undefined`가 들어가 있더라구요! `class="xxx_style undefined"` 이런 식으로요. 그래서 직접 작성할까 라이브러리를 쓸까 하다가 용량도 작고 사용법도 통일 시킬 수 있게 `clsx`를 추가하기로 했습니다.

2024-10-02 10:37 UTC, ptyoiy commented on src/shared/util/form.ts
> +) => {
`dirty`는 값이 입력 됐는지 여부를 나타내고, `touched`는 `blur`가 일어났는지 여부입니다. 해당 부분에서는 figma를 통해 유추할 수 있는 유효성 재검사 로직인 `첫 onBlur 이후 onChange 발생 시 재검사`를 구현하기 위해 사용된 것인데요, `touched`와 `dirty` 둘 다 true면 재검사를 해라! 라는 뜻입니다.

2024-10-02 10:39 UTC, ptyoiy commented on src/shared/component/Form/Form.stories.tsx
> +    });
`zod`를 안 쓰면 컴포넌트 내에서 `max-length`, `type check`, `custom validation` 등의 검사 코드가 추가됐을텐데 이걸 분리할 수 있어 좋은 것 같아요

2024-10-02 10:51 UTC, ptyoiy commented on src/shared/component/Form/index.tsx
정확하게 이해하셨습니다.
트리 구조의 경우 사실 DOM에 렌더링 되는 것은 `FormItem`의 `<div>`와 `Slot`을 통한 `children` 출력 뿐이고 나머지는 `context provider`이긴 합니다.
저도 좀 압축(추상화)시킬 여지가 있지 않나 싶은데, `FormField`에서 label, input, description 등을 `children`으로 받고 이 `children`과 필수 요소인 `FormItem`을 `Controller`의 `render` 속성으로 잘 넣어주면 이것저것 생략할 수 있어 간결하게 만들 수 있을 것 같네요! 한번 시도해보겠습니다.

2024-10-03 12:05 UTC, hwangjokim commented
Input PR 머지된 상태여서 한번 브랜치 최신화 부탁드려요

2024-10-03 15:43 UTC, j-nary requested changes

2024-10-03 15:43 UTC, j-nary commented on src/shared/util/form.ts
> +export const getRevalidationHandlers = <TFieldValues extends FieldValues>() => {
이 아이 `mode="onBlur"` 대신에 `mode="onTouched"` 쓰면 되는 거 아닌가욤?
직접 구현하신 이유가 따로 있으실까요?
`getRevalidationHandler` 함수가 필요없어보입니다!

2024-10-03 16:10 UTC, j-nary requested changes

2024-10-03 16:10 UTC, j-nary commented on src/shared/hook/useFormField.ts
> +};
`FormField` 및 `FormItem` 내부 요소들에게 aria 속성 주기 위해서 사용되는 context api 같아 보이는데, 이 부분 controller에서 제어해줄 수 있지 않을까요? 
context api 사용하지 않아도 controller props로 aria 속성들 받아서 controller의 render에 들어갈 컴포넌트에 직접 할당해줄 수 있을 것 같습니다
특별히 context api를 사용해서 외부에서 주입하는 것을 자동화하신 이유가 있을까요?

2024-10-03 16:10 UTC, j-nary commented on src/shared/util/form.ts
> + */
docs나 PR로 사용법 옮겨주시면 감사하겠습니당!

2024-10-04 03:23 UTC, ptyoiy commented on src/shared/util/form.ts
> + */
옮겼습니다!

2024-10-04 03:32 UTC, ptyoiy commented on src/shared/hook/useFormField.ts
> +};
사용되는 모든 `item`을 한 컴포넌트로 합쳐서 `type`에 따라 `input`, `textarea`, `datepicker` 를 선택하게 하면 jnary님 의견대로 context가 필요 없겠지만, 저는 잘게 분리한 `Form` 요소들을 사용자가 알아서 조립해 쓰면, 하나로 합쳤을 때 만날 수 있는 예외 상황이(구현하려면 합친 컴포넌트의 수정이 필요한) 없을 거라 생각해서 context api를 사용해 자동화 한 것이었습니다.

그런데 figma를 확인해보니 의외로 예외 상황을 다 처리할 수 있겠다는 생각이 들어 `FormController`라는 컴포넌트로 합쳤습니다. 의견 감사합니다!

2024-10-04 04:06 UTC, ptyoiy commented on src/shared/util/form.ts
> +export const getRevalidationHandlers = <TFieldValues extends FieldValues>() => {
확인 감사합니다!

2024-10-04 14:55 UTC, j-nary requested changes

2024-10-04 14:55 UTC, j-nary commented on src/shared/component/Form/index.tsx
> +};
파일 분리 부탁드립니당!

2024-10-04 14:55 UTC, j-nary commented on src/shared/util/form.ts
> +export const getMultipleRevalidationHandlers =
이 아이 필요한가요? `required` 속성 + zod 타입 선언을 통해 여러 필드 유효성 검사 한번에 하는 handler 작업 controller가 할 수 있는 것으로 알고 있습니당

2024-10-04 14:55 UTC, j-nary commented on src/shared/component/Form/index.tsx
> +              />
descriptionPosition === 'top' 일 때와 'bottom' 일 때 동일한 코드가 쓰이는 것 같은데 변수로 빼서 코드 중복 줄이는 건 어떻게 생각하시나요? 
그럼 반환되는 jsx 코드가 좀 더 간결해질 것 같아요!

2024-10-04 14:55 UTC, j-nary commented on src/shared/component/Form/index.tsx
> +        }
어차피 해당 컴포넌트 클라이언트 컴포넌트니까 요 아이들 field를 useState로 저장해서 return문 위에서 선언해서 조립해주면 코드가 더 깔끔해질 것 같아요!
어떻게 생각하시나요?

2024-10-04 15:08 UTC, ptyoiy commented on src/shared/component/Form/index.tsx
> +};
넵 수정했습니다

2024-10-04 15:39 UTC, ptyoiy commented on src/shared/util/form.ts
> +export const getMultipleRevalidationHandlers =
회원가입 폼에서 필요합니다. Form 스토리 중에 `Password Confirm`을 확인해보시면 되는데, 이걸 사용하는 목표와 적용했을 때의 효과는 다음과 같습니다.
- 원하는 기능 (목표)
  - `비밀번호 확인` 검사 시 `비밀번호`도 같이 검사하여 `비밀번호`의 에러 메세지를 공통 `Description`에 우선적으로 표시
- 조건
  - mode: "onTouched"로 첫 blur 및 그 이후 change 이벤트 때 검사
  - `비밀번호 확인`에만 이 handlers를 적용하여 비밀번호 field와 연동되게 만들고, 다른 field들은 mode로 정해준 `onTouched` 검사 방식 사용
  - 기본적으로 zod 스키마 작성 시 `refine` 메서드를 통해 두 값이 다르면 에러가 나게 함

- 이 함수 안 쓰고 적용하기
  - useForm의 반환값 중 `trigger()` 함수를 사용하기 (인자로 넣은 name에 해당하는 field 검사)
    - trigger(['password', 'confirmPassword']) 처럼 사용
    - 결국 이 함수의 구현체처럼 작성해야 동일한 효과를 볼 수 있음

참고로 zod를 사용해서 검사하기에 `required` 속성은 사용할 수 없고, 대신 zod에서 z.string().trim().min(1)로 값이 있는지 검사할 수는 있습니다.

2024-10-04 15:42 UTC, ptyoiy commented on src/shared/util/form.ts
> +export const getMultipleRevalidationHandlers =
Controller의 `rules` 속성은 zod를 사용 중이라 작동하지 않고, render가 제공하는 함수 매개변수는 상태에 관련된 것만 있어서 검사할 수 없네요. 혹시 다른 방법이 있다면 알려주세요!

2024-10-04 15:48 UTC, ptyoiy commented on src/shared/component/Form/index.tsx
> +              />
좋다고 생각해서 적용했습니다

2024-10-04 16:43 UTC, j-nary commented on src/shared/util/form.ts
> +export const getMultipleRevalidationHandlers =
```tsx
  const { register, handleSubmit, trigger, setValue } = useForm({
    mode: "onTouched", // 기본적으로 onTouched를 사용
  });

  const onSubmit = (data: any) => {
    console.log("Form data:", data);
  };

  // 2, 3, 4번 필드에는 onBlur로 유효성 검사를 트리거
  const handleBlur = (fieldName: string) => {
    trigger(fieldName); // 해당 필드의 검증을 onBlur 이벤트에서 실행
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      {/* 1번 필드 - onTouched로 검증 */}
      <div>
        <label>Field 1 (onTouched)</label>
        <input {...register("field1")} />
      </div>

      {/* 2번 필드 - onBlur로 검증 */}
      <div>
        <label>Field 2 (onBlur)</label>
        <input
          {...register("field2")}
          onBlur={() => handleBlur("field2")} // onBlur 이벤트에서 검증
        />
      </div>
```
이런 식으로 필드마다 다른 mode를 적용해줄 수 있을 것 같아용!

2024-10-04 19:38 UTC, ptyoiy commented on src/shared/util/form.ts
> +export const getMultipleRevalidationHandlers =
지금 방식이 제시해주신 방식보다 지금 방식이 더 간단하기에 구조는 이대로 가겠습니다. 다만 context 제거는 찬성입니다. `FormController`가 RHF의 Controller 컴포넌트를 wrapping한 것이다 보니 이것 저것 커스터마이징 하기가 편해서 변경하기도 괜찮더라구요.

기존 구현에서 `useFormContext`를 제거하기 위해 기존에 `FormController`가 받던 `form.control` 대신 `form` 자체를 받아 컴포넌트 내부에서 필요한 속성들을 추출해 적용해주도록 바꾸었습니다. 결과적으로 props의 수는 달라지지 않았고, 사용자는 이전과 똑같이 사용하되 control부분만 form으로 변경해주면 되면서 성능적으로 미미한 이점이 생겼네요.

2024-10-04 20:15 UTC, j-nary approved these changes
고생하셨슴다 LGTM !

2024-10-04 20:40 UTC, merged