[ Feat ] Sidebar 컴포넌트 구현 및 탭 Icon prop 방식 수정
GAMZA-BAT/algohub-client pull request #67
Opened 2024-10-03 11:42 UTC by wuzoo

## #️⃣ Related Issue
Closes #55

## ✅ Done Task
  - [x] Sidebar 구현
  - [x] 레이아웃 -> 라우트 or 패널로 관리

## 💎 PR Point

### Tab 수정

1. TabPanels
먼저 기존에 TabPanels는 `section` 태그로 한 번 감싸주고 `aria` 같은 속성들을 주입하여 하위 패널 요소를 렌더링하게 하였는데, `width`나 `height`를 조정하는 단계에서 한 단계 상위의 `section` 요소가 영향을 끼치게 되었습니다. 따라서 그냥 `panel`을 렌더링하되 `cloneElement`를 통해 필요한 속성들을 주입했습니다.

2. Tab Icon prop
기존에는 `svg`를 고려하지 않고 일단은 `svgr` 아이콘을 받아서 렌더링하는 방식을 취했었는데, 동적으로 svg 색상을 입히는 과정에서 많이 불편하더라구요 ! 그래서 `renderProps` 패턴을 통해서 밖에서 주입하도록 하였습니다. 

```ts
// Tab 사용처
<TabGroup.Tab
          renderedIcon={(className: string) => (
            <IcnSquare className={className} width={24} height={24} />
          )}
          tabId="1"
          mode="fill"
        >

// Tab 구현
{renderedIcon
        ? renderedIcon?.(
            iconStyle({
              variant: isSelected ? mode : (`none${mode}` as TabProps["mode"]),
            })
          )
        : null}
```
`mode`라는 추가적인 `prop`을 받도록 수정하였습니다. 왜냐면 결국에는 구현체인 `Tab` 컴포넌트 쪽에서, 지금 주입된 `icon` 요소가 `fill`을 바꿀 것인지 `stroke`를 바꿔야하는지 알아야 하기 때문에 추가적인 프롭을 생성하였습니다.
`renderProp`에서는 해당 `prop`을 실행시켜 렌더링하는 과정에서 `className`을 인자로 받게 하여, 각각의 아이콘들이 `mode`에 따른 스타일을 가질 수 있도록 구현하였어요 !

https://github.com/user-attachments/assets/cbdf8f8f-e9e6-401c-9708-bffa0495a35d

보시다시피 잘 구현되는 모습을 볼 수 있었습니다.

### SideBar 컴포넌트 퍼블리싱

사이드바는 비교적 간단했습니다. 단순 퍼블리싱이였고, 문제는 저희가 카톡으로 짧게 논의했던 `패널을 갈아끼는 형태 vs 라우트 이동`이였습니다. 일단은 저는 패널을 통해 하위 페이지를 갈아끼우는 형식으로 구현하였고, 라우트로 구현이 가능한지는 한 번 파악해본 후 수정하겠습니다.

라우트 이동에 대한 제 생각은 일단 아래와 같습니다.
1. 탭을 누를 때마다 `url`을 갈아끼우려면 `Tab` 컴포넌트를 거의 갈아 엎어야합니다. 왜냐하면 현재 `selected`된 탭이 무엇인지에 따라 패널을 보여주는 형식인데, 결국엔 클릭 이벤트를 감지하여 특정 라우트로 `router.push`가 일어나야하기 때문에 수정이 필요할 것 같습니다.
2. 클릭 이벤트가 발생하여 라우트 이동이 발생한다면 탭을 포함한 모든 컴포넌트가 다시 렌더링되지 않을까하는 우려가 있습니다. 또한 새로운 `url`로 이동하는 과정에서 저희가 구현하고자 했던 탭 인터랙션도 문제가 없을지 장담하지 못하겠네요 !

## 📸 Screenshot

https://github.com/user-attachments/assets/1bfb1063-9312-4837-9850-146c484b99ff

2024-10-05 17:16 UTC, ptyoiy reviewed
LGTM!
간단한 리뷰 및 제 라우트 탭 실험을 확인해주세요.

2024-10-05 17:17 UTC, ptyoiy commented on src/common/component/Tab/Tab.tsx
>      <li
`li`태그의 `tabIndex`가 항상 -1이네요. `selectedTabId`가 `tabId`와 동일할 때 선택 가능 하도록 `tabIndex` 조건을 넣어주세요!

2024-10-05 18:15 UTC, ptyoiy commented
라우트 방식으로 잘 동작할 지 user페이지를 기반으로 실험해봤습니다. 
**조건**에는 제가 적용을 위해 간단하게 변경한 사항을,
**결과**에는 화면 및 devtools로 dom 변화를 영상으로 준비했습니다.

- **조건**
1. `app/user/layout.tsx`
```tsx
export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <TabGroup.Tabs>
        <TabGroup.TabList>
          <TabGroup.Tab tabId="1">dashboard</TabGroup.Tab>
          <TabGroup.Tab tabId="2">create</TabGroup.Tab>
          <TabGroup.Tab tabId="3">join</TabGroup.Tab>
          <TabGroup.Tab tabId="4">setting</TabGroup.Tab>
        </TabGroup.TabList>
      </TabGroup.Tabs> // TabPanels는 안 써도 되겠더군요
      <main style={{ display: "flex" }}>
        <Sidebar>sidebar</Sidebar>
        <section>
          <div style={{ color: "white" }}>{children}</div>
        </section>
      </main>
    </>
  );
}
```
2. `TabProvider.tsx`
```typescript
export const tabIdToPathArray = [
  "/user", // tabId: "1"
  "/user/create-group", // tabId: "2"
  "/user/join-group", // tabId: "3"
  "/user/setting", // tabId: "4"
];

const TabProvider = ({ variant = "primary", children }: TabProviderProps) => {
  const path = usePathname();
  const [state, dispatch] = useReducer<Reducer<State, Actions>>(reducer, {
    variant,
    selectedTabId: `${tabIdToPathArray.indexOf(path) + 1}`, // url 접근 시 해당 탭 활성화
  });
  useEffect(() => {
  // 브라우저의 이전/다음 페이지 버튼 대응
    dispatch({
      _TAG: "SetSelectedTab",
      tabId: `${tabIdToPathArray.indexOf(path) + 1}`,
    });
  }, [path]);
...
```
3. `Tab.tsx`
```typescript
// tab `<li>`의 onClick
onClick={() => {
  router.push(tabIdToPathArray[+tabId - 1]); // tab 클릭 시 route 변경
  dispatch({ _TAG: "SetSelectedTab", tabId });
}}
```
- 결과
1. 화면 - `<Link>`, `router.push`, `url 접근` 전부 잘 작동
![tab](https://github.com/user-attachments/assets/1422914e-e245-41b3-99b7-86251f9470b4)

2. devtools - 전체 DOM을 바꾸지 않는 것으로 확인
![tabdev](https://github.com/user-attachments/assets/fb5c9beb-5e7e-4f8c-a262-6d05a4a77fa3)

- 문제점
dispatch가 중복 호출되는 문제 때문인지 리렌더링이 좀 일어남
  - 탭 클릭 시 : 3~4회
  - 브라우저의 이전/다음 페이지 버튼 : 2회
  - `<Link>`로 이동 시 : 2~3회

결과적으로 route 방식을 사용할 순 있겠는데, 수정이 좀 많아질 것 같네요. 이건 회의 때 논의해보도록 해요.

2024-10-07 15:42 UTC, j-nary requested changes
이전 5차 FE 회의 때 탭 라우팅 방식 사용하기로 하면서 NavBar 로 마이그레이션 진행한다고 하신 부분
진행해주시면 될 것 같습니다 !!

2024-10-08 08:59 UTC, wuzoo commented
그럼 기존의 상태를 통해 하위 컴포넌트를 렌더링하는 방식의 `Tab`은 그대로 유지하되, 라우팅을 통해 탭 관리하는 `NavBar` 컴포넌트를 하나 더 만들면 되는 걸까요 ?

2024-10-09 06:22 UTC, ptyoiy approved these changes

2024-10-09 09:08 UTC, hwangjokim approved these changes

2024-10-09 11:18 UTC, j-nary approved these changes

2024-10-09 11:21 UTC, merged