[ Feat ] JoinGroup 퍼블리싱
GAMZA-BAT/algohub-client pull request #75
Opened 2024-10-04 21:15 UTC by j-nary

## #️⃣ Related Issue
Closes #74 

## ✅ Done Task
  - [x] svg 추가
  - [x] 라우팅 Modal 고민
  - [x] GroupInfoCard 구현
  - [x] 그 외 퍼블리싱

## ☀️ New-insight

- 두줄까지만 나타나고 그 이후 ellipsis 처리하는 거 새롭게 알게 됐습니다!
  ```tsx
  width: "17.4rem",
  height: "auto", // 높이를 자동으로 설정하여 텍스트 내용에 맞추기

  overflow: "hidden",
  display: "-webkit-box",
  WebkitBoxOrient: "vertical", // 수직으로 박스를 나누는 방식
  WebkitLineClamp: 2, // 최대 두 줄까지만 표시
  textOverflow: "ellipsis", // 넘치는 부분에 '...' 표시
  ```

- `line-clamp` 브라우저 호환성에 따라 구현방식 조금 다를 수 있다길래 여러 브라우저에서 (특히, Safari) 테스트 해봤는데 문제 없는 거 확인했습니다!
  <img width="1185" alt="image" src="https://github.com/user-attachments/assets/50755d5a-fb8b-4710-9972-2fa0e524cab7">

## 💎 PR Point

- 해당 PR 코드리뷰하시면서 라우팅 모달 어떻게 해야하는지 익혀가시면 좋을 것 같아요!

## 📸 Screenshot

https://github.com/user-attachments/assets/f07ec2a9-a870-457c-9228-d44d75f393dc

2024-10-07 13:48 UTC, ptyoiy requested changes
고생 많으셨습니다! 몇 가지 수정 요청 사항이 있으니 확인해주세요

2024-10-07 13:49 UTC, ptyoiy commented on src/app/user/join-group/page.tsx
> +          <Link href="/user">
문구가 없기 때문에 `aria-label`속성을 부여해서 link의 의미를 알려줘야 합니다.

2024-10-07 13:52 UTC, ptyoiy commented on src/view/user/join-group/component/DecisionPrompt/index.tsx
> +    </section>
`<section>`을 사용했는데 h1~h6 태그가 없으니 어색하군요. 스터디 수락 문구를 `h2`?로 하는 건 어떨까요?

2024-10-07 13:58 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +    <section className={groupDateInfoWrapper}>
`<section>`은 문서 내 독립적인 섹션을 의미합니다. 논리적으로 의미 있는 구획을 나타내는 것이지요. 
대강 **h1~h6 태그가 필요한가?**로 `section` 태그 사용 여부를 파악하면 되겠습니다.

시간을 알려주는 용도 만으로는 섹션을 나눌 필요 없고, `<div>`로 묶어주면 될 것 같습니다.

2024-10-07 13:59 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +      <span className={groupDateStyle}>{startDate}</span>
시간 관련 태그는 `<time datetime={날짜}>` 사용해 주세요.
스크린리더가 읽을 때 `이천이십사 점 영팔 점 십삼`으로 읽을 여지가 있습니다.

2024-10-07 14:07 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +      <section className={infoWrapper}>
16번 라인이나 여기 중 한 곳만 `<section>`을 사용하는 게 좋겠습니다. 의미 있는 구획 나누기가 아닌, 단순 flex wrapping  부분을 제거하고 div로 변경하는 게 좋겠어요.

2024-10-07 14:07 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +      <section className={infoWrapper}>
groupNameStyle 을 적용한 `<p>`도 `h1~h6` 태그로 변경하면 좋겠네요.

2024-10-07 14:12 UTC, ptyoiy commented on src/app/user/join-group/page.tsx
> +        <section className={wrapper}>
아래쪽의 `DecisionPrompt`에서 `section`으로 의미 없이 두 번 섹션을 나누지 말고, 여기 사용된 `section`에 들어가게 하는 게 논리적으로 이상적인 구획 나누기가 아닐까 합니다. 즉, `DecisionPrompt`에 사용된 `section`을 `div`로 교체하고 스터디 수락 문구를 `p` 대신 `h1~h6` 태그로 하는 게 좋지 않을까요?

2024-10-07 14:21 UTC, ptyoiy commented on src/app/user/join-group/page.tsx
> +        <section className={wrapper}>
근데 이렇게 하면
```html
<section>
  <section /> // 카드
  <div> // 수락 프롬프트
    <h2> // 스터디 수락? 문구
     ...
  </div>
</section>
``` 
형태가 되어 제목 전에 `section`이 나와버리는 별로 좋지 못한 구획 나누기가 될 것 같네요. 32번 라인(가장 바깥쪽 section)을 `div`로 하고 `DecisionPrompt`에서 `section`을 쓰는 게 좋을 것 같아요!

2024-10-07 16:00 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          <Link href="/user">
네! 좋은 피드백 감사합니당

2024-10-07 16:06 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +    <section className={groupDateInfoWrapper}>
h1~h6 태그가 필요한 구획은 `article` 태그,
h1~h6 태그까진 필요없지만 외부와 어느정도 분리되면 `section` 태그라고 생각했습니다
구획의 논리성없이 단순 스타일링 목적이면 `div` 태그가 맞지만,
해당 부분은 `그룹의 duration(시작 시간, 끝 시간)` 을 의미하는 구획이라고 생각해서 `section` 태그를 사용했던 것인데 ..
시맨틱 태그에 대해 공식문서도 찾아봤지만 추상적이라 어렵네요
좋은 피드백 감사합니다 :)

2024-10-07 16:08 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +      <span className={groupDateStyle}>{startDate}</span>
헉 time 태그가 있었다니! 덕분에 알아갑니다 감사합니다 :)

2024-10-07 16:10 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +      <section className={infoWrapper}>
네! 동의합니다! 좋은 피드백 감사합니다 :)

2024-10-07 16:13 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +        <section className={wrapper}>
코리를 통해 시맨틱 태그에 대해 더 깊게 알아갑니다
감사해요 !

2024-10-07 16:36 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +    <section className={groupDateInfoWrapper}>
`article`과 `section` 둘 다 h를 필요로 합니다. 둘 간의 차이는 검색해보면 많은 자료가 나오니 찾아보시는 것도 좋겠네요!

이 [문서](https://html5doctor.com/the-section-element/)의 내용 중 `Rules of thumb for using section`부분에 따르면 스타일링 용으로는 `div`를, 제목을 안 쓸거면 `section`을 쓰지 말라고 합니다.

2024-10-07 16:37 UTC, ptyoiy commented on src/app/user/join-group/page.tsx
> +              role="button"
이거 Link에 달면 role을 안 붙여도 됩니다!

2024-10-07 16:40 UTC, ptyoiy commented on src/view/user/join-group/component/DecisionPrompt/index.tsx
> +      <h2 className={descStyle}>
여기 섹션은 제목-제목보다는 제목과 내용을 의미하는 것이 더 옳을테니 h2까지는 안 써도 괜찮을 것 같습니다.

2024-10-07 16:42 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +        <h4 className={descStyle}>{description}</h4>
여기도 제목이 아니니까 p태그 유지하시는 게 좋겠습니다

2024-10-07 16:48 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +              role="button"
좋은 정보 감사합니다!

2024-10-07 16:49 UTC, j-nary commented on src/view/user/join-group/component/DecisionPrompt/index.tsx
> +      <h2 className={descStyle}>
앗 네 ! 감사합니다

2024-10-07 16:50 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +        <h4 className={descStyle}>{description}</h4>
<img width="707" alt="image" src="https://github.com/user-attachments/assets/a461d5e4-8873-439d-9b6c-3cbd38ffe422">
2시간 전에는 h1 ~ h6 태그로 변경하라고 하셨잔하효 ...?

2024-10-07 16:58 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
> +    <section className={groupDateInfoWrapper}>
아하! 감사합니당 :)

2024-10-07 17:04 UTC, ptyoiy commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +        <h4 className={descStyle}>{description}</h4>
groupNameStyle 을 적용한 <p>는  `<p className={groupNameStyle}>{name}</p>`이거 하나라서 저렇게 작성했었습니다..

2024-10-07 17:05 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +        <h4 className={descStyle}>{description}</h4>
아항! 덕분에 h 태그에 대해 깊게 고민해볼 수 있었던 기회였습니당 감사합니다 :)

2024-10-07 17:06 UTC, ptyoiy approved these changes
고생 많으셨습니다!

2024-10-07 17:06 UTC, wuzoo reviewed
고생하셨슴다 ~~ 🚀🚀🚀

2024-10-07 17:06 UTC, wuzoo commented on src/view/user/join-group/component/GroupInfoCard/index.css.ts
> +});
요것도 `~Style` 컨벤션 지켜주세용 ~

2024-10-07 17:06 UTC, wuzoo commented on src/view/user/join-group/component/DecisionPrompt/index.tsx
> +      <h1 className={metaStyle}>스터디를 수락하시겠어요?</h1>
`Heading` 많이 쓰일 것 같은데 공통으로 하나 만들어주어도 좋을 듯... 싶습니당

2024-10-07 17:06 UTC, wuzoo commented on src/app/user/join-group/page.tsx
> +          </Link>
이거 닫는 버튼인데 모달에서 닫는 버튼은 하나의 디자인을 가지니까 모달에 박아놔도 좋을 것 같아요. 즉 `useOutClickSide`의 동작이랑 `closebtn` 클릭이랑 똑같은 동작이므로, 모달에서 `CloseBtn` 컴포넌트를 렌더링한다음에 그냥 눌렀을 때 `onClose` 실행시키면 될 것 같습니다.

닫는 버튼이 없는 모달도 있을테니까 `hasCloseBtn` 정도 prop으로 처리할 수 있을 것 같네요

2024-10-07 17:06 UTC, wuzoo commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +    </section>
카드는 `section` 보다는 div 로 처리하거나 `article` 정도의 태그가 더 잘 어울릴듯 싶어요

2024-10-07 17:10 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          </Link>
모달마다 `closeBtn`의 위치가 달라서 그렇게 처리하지 않았습니다 ..!

2024-10-07 17:12 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/index.tsx
> +    </section>
넵 좋은 피드백 감사합니다 ! 반영하겠습니다 :)

2024-10-07 17:13 UTC, j-nary commented on src/view/user/join-group/component/DecisionPrompt/index.tsx
> +      <h1 className={metaStyle}>스터디를 수락하시겠어요?</h1>
지난 client 3차 회의에서 text 관련 공통 컴포넌트 만들지 않기로 결론 났었습니당 !
타이포시스템이 있기 때문입니당

2024-10-07 17:23 UTC, j-nary commented on src/view/user/join-group/component/GroupInfoCard/index.css.ts
> +});
넹! 컨벤션 제안 감사드림니당 :)

2024-10-08 07:17 UTC, wuzoo commented on src/app/user/join-group/page.tsx
> +          </Link>
저는 같은게 이상적이라고 생각하긴 해요. 디자인에서 패딩값이 일부분 다른거라면 디자이너분께 통일해달라고 말씀드려도 될 것 같습니다.

2024-10-08 07:17 UTC, wuzoo commented on src/app/user/join-group/page.tsx
> +          </Link>
적어도 모달의 사용처에서 모달에 관한 클로즈버튼을 렌더링하는 행위는 나쁜 것 같슴니다..

2024-10-08 08:45 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          </Link>
크기가 모달마다 달라서 패딩값을 동일하게 가져가면 디자인상 예쁘지 않을 것 같아요
closeBtn이 없는 경우도 있어서 ...
Modal 컴포넌트 내부에서 `showCloseBtn` , `closeBtnStyle` 을 prop으로 받는 것이 좋다고 생각하시는지 궁금합니다!

2024-10-08 08:55 UTC, wuzoo commented on src/app/user/join-group/page.tsx
> +          </Link>
크기가 달라도.. 패딩값은 같아야 하지 않을까요 ? 패딩값이 만약 다르게 디자인이 되어야 한다고 해도 클로즈 버튼은 또 고정된 위치에 있어야 할 것 같다고 생각하긴 합니답 .. 음

디자이너분이랑 이야기좀 해보면 좋을 것 같구, `closeBtn`이 있고 없고는 `boolean` prop 하나 넘기면 될 것 같습니다. `onClick` 핸들러는 `onClose`로 동일하구요

2024-10-08 12:26 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          </Link>
네! 반영하겠습니다 좋은 피드백 감사합니다 :)

2024-10-08 23:42 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          </Link>
적용하려고 보니, dialog는 `position: fixed` 이어서 x버튼을 `position: absolute`로 구현할 수 없는 문제가 있습니다.
x버튼도 `position: fixed`로 위치 조정하기엔, 모달이 크기마다 달라서 조정할 수 없을 것 같습니다.
혹시 기가막힌 아이디어가 있으실까요?

2024-10-09 15:28 UTC, j-nary commented on src/app/user/join-group/page.tsx
> +          </Link>
`<section>` 태그 추가해서 반영했습니다 ! 확인해주세요:)

2024-10-09 15:34 UTC, wuzoo approved these changes

2024-10-09 15:35 UTC, merged