Feat/#53/login page
GAMZA-BAT/algohub-client pull request #76
Opened 2024-10-06 21:45 UTC by ptyoiy

## #️⃣ Related Issue
Closes #53 

## ✅ Done Task
  - [ ] 로그인 페이지 구현
  - [ ] 유효성 검사 적용

## ☀️ New-insight

- `<Link>`, `router.push` 사용 시 `scroll: false` 옵션
두 방식을 사용해 페이지를 이동할 때 [문서](https://nextjs.org/docs/app/api-reference/functions/use-router#disabling-scroll-to-top) 기본적으로 페이지 상단으로 스크롤한다고 합니다. 이 때 다음 페이지에서 `position: sticky`나 `fixed`를 사용할 경우(modal) css 충돌?이 일어나 warning이 뜨는데, 이를 방지하기 위해 `router.push('/dashboard', { scroll: false }` 이런 식으로 옵션을 추가해주면 됩니다.

## 💎 PR Point

- 유효성 검사 로직
id, password 둘 다 검사해서 둘 중 하나라도 오류가 있으면 상단에 에러메세지를 표시해야 합니다. 이를 위해 `!!Object.keys(form.formState.errors).length`를 사용하여 명시적으로 `id description`에 `error` 상태를 넣어주었습니다. 
메세지의 경우 스키마 파일에서 매 메서드 체인마다 전부 동일한 메세지(id, pw 확인)를 넣어주기보단 컴포넌트쪽에서 에러 발생 여부에 따라 메세지 constant를 입력하도록 했습니다.
```typescript
  const isError = !!Object.keys(form.formState.errors).length;
  const message = isError ? loginSchemaMessage : undefined;
```
```tsx
<FormController
 ...
  name="id"
  showDescription
  descriptionPosition="top"
  descriptionProps={{
    isError,
    message,
  }}
/>
```
## 📸 Screenshot

![loginpage](https://github.com/user-attachments/assets/aae8da17-f086-4dca-a070-f11aa8908b5b)

2024-10-06 21:56 UTC, ptyoiy commented
로그인 PR 머지 후에 회원가입 PR을 올리겠습니다. 회원가입 브랜치의 경우 로그인 브랜치에서 만든 `view/index/component` 공통 파일을 사용하고 있어서 파일 변경 사항이 로그인 브랜치의 것 까지 나타나 불편할 것이라 생각합니다.

2024-10-07 15:35 UTC, j-nary requested changes
LGTM!! 코드 깔끔해서 넘모 좋네용 코리 몇개만 확인해주시면 감사하겠습니당 !

2024-10-07 15:35 UTC, j-nary commented on src/app/layout.tsx
> -import "@/styles/globalStyles.css";
이거 왜 지우시는 건가요?

2024-10-07 15:35 UTC, j-nary commented on src/app/login/page.tsx
> +      <AuthHeader handleClick={onClose} />
Header 아래 구분선의 색상이 디자인과 다른 것 같아요!
아래 피그마 캡처본 첨부할게요 (아예 흰색이 아닌 그라데이션 처럼 보이네요)
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/0ca7501a-3f5d-474f-9aa9-a9cf0ef253c5">

2024-10-07 15:35 UTC, j-nary commented on src/app/login/page.tsx
> +        </Card>
Button disabled 처리(아래 코드 적용)가 안 되는 것 같은데 확인 부탁드려도 될까요 ..?
```tsx
    ":disabled": {
      opacity: "0.7",
      cursor: "not-allowed",
    },
```

2024-10-07 15:35 UTC, j-nary commented on src/app/login/page.tsx
> +    router.back();
`router.push('/')` 에 의견 한 표 던집니다.
외부 사이트에 있다가 로그인 path 받아서 바로 들어온 사용자의 경우 `router.back()` 을 해서 서비스를 이탈시키는 건 크리티컬한 문제이기 때문입니다.

2024-10-07 15:35 UTC, j-nary commented on src/shared/component/Header/LoginMenu.tsx
LoginMenu는 Header에서 쓰이지만, 여러 domain에 공유되는 것이 아닌 온보딩 페이지에서만 사용되는 것이기 때문에 view 폴더로 옮겨도 좋을 것 같아요 어떻게 생각하시나요?

2024-10-07 15:37 UTC, ptyoiy commented on src/app/layout.tsx
> -import "@/styles/globalStyles.css";
파일 변경이 조금 이상하게 잡혔는데 위로 올라간 겁니다! 3번 라인에 있어요

2024-10-07 15:55 UTC, ptyoiy commented on src/app/login/page.tsx
> +      <AuthHeader handleClick={onClose} />
figma 상으로는 저 bottom border가 그라데이션 없이 mg5 색상을 쓰고 있습니다. figma의 버그로 뒷 배경색에 색이 섞여서 저렇게 나오는 것 같은데, 디자이너님이 figma에 작성한 속성대로 쓰는 것이 맞지 않을까요?

2024-10-07 15:57 UTC, ptyoiy commented on src/app/login/page.tsx
> +        </Card>
어째 기본 값으로 opacity 0.7을 넣어놨네요. 확인 감사합니다!

2024-10-07 16:13 UTC, ptyoiy commented on src/shared/component/Header/LoginMenu.tsx
`view` 폴더는 `page.tsx`에 들어갈 컴포넌트를 놓는 곳이었죠. 저는 이 `LoginMenu`가 헤더 즉, `layout.tsx`에 들어갈 컴포넌트이지 `page`에 들어갈 컴포넌트가 아니니까 view로 옮기지 않아도 된다고 생각합니다.

2024-10-07 16:20 UTC, j-nary commented on src/shared/component/Header/LoginMenu.tsx
하지만, 여러 domain에서 `shared` 되는 부분이 아니니까 `shared` 에 놓을 필요 없다고 생각합니다!
`shared` 의 폴더 의미 자체가 여러 domain에서 겹치는 부분을 모아둔 곳이기 때문에
`view`로 옮기는게 맞다고 생각해요 :)

2024-10-07 16:25 UTC, j-nary commented on src/app/login/page.tsx
> +      <AuthHeader handleClick={onClose} />
뷰가 달라서 남긴 리뷰였습니당
이렇게 애매한 부분은 디자이너 분과 소통하시면 좋을 것 같아요!
우선 제가 피그마에서 해당 부분 요청 드려놨으니 달린 답글 보시고 작업 진행해주시면 좋을 것 같아요 :)

여담으로, figma에 작성된 속성은 참고용이고, 보이는 뷰가 우선시 되어야한다고 생각합니당 ~

2024-10-07 16:44 UTC, ptyoiy commented on src/app/login/page.tsx
> +      <AuthHeader handleClick={onClose} />
답글이 늦는다면 일단 이 부분은 넘어가고 나중에 새 이슈를 파는 게 좋겠네요. 감사합니다!

2024-10-07 16:46 UTC, ptyoiy commented on src/shared/component/Header/LoginMenu.tsx
앗 `index.tsx`로 내보내는 파일만 그 `shared` 폴더 조건에 해당되는 게 아니었나요? 그렇다면 view로 옮기는 게 낫겠네요.

2024-10-07 17:41 UTC, j-nary approved these changes

2024-10-07 18:41 UTC, j-nary commented on src/view/login/component/LoginForm/index.tsx
> +  const onSubmit = (_values: z.infer<typeof loginSchema>) => {
네이밍 컨벤션에 맞게 `handleSubmit` 으로 수정 부탁드릴게요!

2024-10-07 18:41 UTC, j-nary commented on src/view/login/component/LoginForm/index.tsx
> +        <SubmitButton disabled={disabled}>로그인하기</SubmitButton>
form 이랑 id 맞춰줘야 submit되지 않나요?

2024-10-07 18:46 UTC, ptyoiy commented on src/view/login/component/LoginForm/index.tsx
> +        <SubmitButton disabled={disabled}>로그인하기</SubmitButton>
그냥 form 태그 안에서 `<button type="submit" />` 인 녀석을 클릭하면 submit 이벤트가 발생해요

2024-10-07 18:46 UTC, ptyoiy commented on src/view/login/component/LoginForm/index.tsx
> +  const onSubmit = (_values: z.infer<typeof loginSchema>) => {
넵 알겠슴다

2024-10-07 20:41 UTC, j-nary commented on src/view/login/component/LoginForm/index.tsx
> +        <SubmitButton disabled={disabled}>로그인하기</SubmitButton>
헉! 유용한 정보 완전 감사합니다 :)

2024-10-08 07:15 UTC, wuzoo reviewed
고생하셨슴다 ~~~~

2024-10-08 07:15 UTC, wuzoo commented on src/view/index/component/AuthHeader/index.tsx
이 컴포넌트와 `Card`는 왜 `index` 하위에 있는거죵 ? 로그인 뷰에서 쓰이는 컴포넌트들 아닌가요 ?

2024-10-08 07:15 UTC, wuzoo commented on src/view/login/component/Container/index.tsx
컨테이너와 헤딩 컴포넌트는 분리를 안해주어도 될 것 같아요 .. ! 단 특별한 prop도 없고, 자식이나 하나의 JSX 요소만을 반환하니 사용처에서 그냥 작성해주어도 될 것 같은데 어떻게 생각하시나요 ??

2024-10-08 07:15 UTC, wuzoo commented on src/view/login/component/LoginForm/index.tsx
> +  const onSubmit = (_values: z.infer<typeof loginSchema>) => {
에러나 활성화 상태, 폼 관리 로직 등 하나로 `useLoginForm`과 같은 커스텀 훅으로 관리해주면 더욱 깔끔해질 것 같아용 !

2024-10-10 01:35 UTC, ptyoiy commented on src/view/index/component/AuthHeader/index.tsx
`AuthHeader`는 signup page와 공용으로 사용하고, `Card`는 [마이페이지-my profile](https://www.figma.com/design/PBHmaVSKndAId6lY6G2qEb/AlgoHub?node-id=491-25210&t=54eXlZ77sZc4i4Rc-4)탭과 공용으로 사용됩니다.

2024-10-10 01:48 UTC, ptyoiy commented on src/view/login/component/Container/index.tsx
다른 분은 어떻게 했나 확인해보니 `index.css.ts`를 `view/[route]/component`에 놓고 사용하는군요. 폴더 구조 리팩토링 pr의 내용대로 `component` 폴더에 다른 파일 없이 컴포넌트 폴더만 있어야 할 것 같아서 이렇게 했던 건데, 분리 없이 스타일만 가져오도록 `component/index.css.ts`를 써도 된다면 그렇게 하겠습니다.

2024-10-10 01:51 UTC, ptyoiy commented on src/view/login/component/LoginForm/index.tsx
> +  const onSubmit = (_values: z.infer<typeof loginSchema>) => {
반영했습니다

2024-10-10 23:18 UTC, closed without merging